import type {
  ReadinessBlogRegistryEntry,
  ReadinessFrameworkRegistryEntry,
} from "@/lib/readiness-content-types";

export const readinessBlogRegistry: readonly ReadinessBlogRegistryEntry[] = [
  {
    slug: "video-companion-q-day-explained",
    kind: "video-companion",
    markdownFile: "blog/video-companion-q-day-explained.md",
    title: "After Q-Day Explained: what mid-market CISOs should do this quarter",
    description: "Original takeaways from a popular Q-Day video — CRQC timelines, HNDL exposure, and inventory steps.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "Q-Day timeline illustrating post-quantum cryptography risk.",
    excerpt: "Original takeaways from a popular Q-Day explainer — plus what to do this quarter.",
    readiness: true,
  },
  {
    slug: "video-companion-hndl-jeremy-allison",
    kind: "video-companion",
    markdownFile: "blog/video-companion-hndl-jeremy-allison.md",
    title: "After Jeremy Allison on HNDL: what your security team should do now",
    description: "Practitioner insights on harvest-now-decrypt-later and how to quantify exposure before Q-Day headlines.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "Harvest-now-decrypt-later exposure timeline.",
    excerpt: "Practitioner insights on HNDL — and how to inventory before migration finishes.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "video-companion-pq-algorithms-nist",
    kind: "video-companion",
    markdownFile: "blog/video-companion-pq-algorithms-nist.md",
    title: "After the NIST PQC algorithms video: your ML-KEM migration checklist",
    description: "ML-KEM, ML-DSA, and SLH-DSA in plain language — with hybrid TLS as the near-term path.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Post-quantum algorithm standards overview.",
    excerpt: "ML-KEM, ML-DSA, and SLH-DSA in plain language — with a migration checklist.",
    readiness: true,
  },
  {
    slug: "spreadsheet-crypto-inventory-wrong",
    kind: "blog",
    markdownFile: "blog/spreadsheet-crypto-inventory-wrong.md",
    title: "Why your spreadsheet crypto inventory is wrong",
    description: "Manual TLS inventories miss drift, JWKS, STARTTLS, and re-scan verification.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Spreadsheet versus live cryptographic inventory comparison.",
    excerpt: "Manual TLS inventories miss drift, JWKS, and STARTTLS — why spreadsheets fail.",
    readiness: true,
  },
  {
    slug: "reading-qtangl-cbom-export",
    kind: "blog",
    markdownFile: "blog/reading-qtangl-cbom-export.md",
    title: "Reading a Qtangl CBOM export: field-by-field guide",
    description: "Walk through a sample CycloneDX Crypto Bill of Materials — algorithms, assets, and GRC integration.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "CycloneDX CBOM export fields and remediation mapping.",
    excerpt: "Walk through a sample CBOM JSON — algorithms, assets, and GRC integration.",
    readiness: true,
  },
  {
    slug: "mosca-inequality-for-cisos",
    kind: "blog",
    markdownFile: "blog/mosca-inequality-for-cisos.md",
    title: "Mosca inequality explained for CISOs",
    description: "Turn Mosca's X + Y > Z into a board-ready planning question for HNDL exposure.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "Mosca inequality X plus Y greater than Z diagram.",
    excerpt: "Turn Mosca's X + Y > Z into a board-ready planning question.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "cmmc-crypto-inventory-evidence",
    kind: "blog",
    markdownFile: "blog/cmmc-crypto-inventory-evidence.md",
    title: "CMMC crypto controls: inventory evidence auditors want",
    description: "What CMMC Level 2 assessors expect — inventory artifacts, not slide decks.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "CMMC Level 2 cryptographic inventory evidence checklist.",
    excerpt: "What CMMC assessors expect — inventory artifacts, not slide decks.",
    readiness: true,
  },
  {
    slug: "crypto-flip-orchestration-2026",
    kind: "blog",
    markdownFile: "blog/crypto-flip-orchestration-2026.md",
    title: "Crypto flip orchestration: prove the change in your CLM and KMS",
    description: "Orchestrate overlay, CLM, and KMS flips with dry-run, approval, and signed before/after evidence.",
    category: "Convert",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Crypto flip orchestration workflow.",
    excerpt: "Qtangl orchestrates the flip in your systems and proves it — without a PQ overlay appliance.",
    readiness: true,
  },
  {
    slug: "crypto-drift-monitoring-2026",
    kind: "blog",
    markdownFile: "blog/crypto-drift-monitoring-2026.md",
    title: "Unified crypto drift monitoring in 2026",
    description: "Snapshots across external, host, code, and CBOM sources with SIEM-ready webhooks.",
    category: "Monitor",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Unified crypto drift monitoring dashboard.",
    excerpt: "Drift is not just TLS scan diff — unified snapshots across discovery sources.",
    readiness: true,
  },
  {
    slug: "crypto-drift-one-scan-not-enough",
    kind: "blog",
    markdownFile: "blog/crypto-drift-one-scan-not-enough.md",
    title: "Crypto drift: why one scan is not enough",
    description: "A baseline scan satisfies this quarter's board slide — it does not catch next week's deployment.",
    category: "Monitor",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Crypto drift diff between consecutive scans.",
    excerpt: "Why a baseline scan decays — and how Monitor catches regression.",
    readiness: true,
  },
  {
    slug: "q-day-monitor-alerts-setup",
    kind: "blog",
    markdownFile: "blog/q-day-monitor-alerts-setup.md",
    title: "Setting up Q-Day Monitor alerts",
    description: "Configure re-scan cadence, drift alerts, and readiness score trends.",
    category: "Monitor",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Monitor alert configuration for crypto drift.",
    excerpt: "Configure re-scan cadence, drift alerts, and readiness score trends.",
    readiness: true,
  },
  {
    slug: "remediation-backlog-deadline-prioritization",
    kind: "blog",
    markdownFile: "blog/remediation-backlog-deadline-prioritization.md",
    title: "Remediation backlog prioritization by deadline tier",
    description: "Prioritize PQC fixes by NSM-10, CNSA 2.0, and data shelf-life — not gut feel.",
    category: "Convert",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "Remediation backlog prioritized by compliance deadline tier.",
    excerpt: "Prioritize fixes by NSM-10, CNSA 2.0, and data shelf-life.",
    readiness: true,
  },
  {
    slug: "hybrid-tls-handshake-appendix",
    kind: "blog",
    markdownFile: "blog/hybrid-tls-handshake-appendix.md",
    title: "Hybrid TLS proof: what the handshake appendix means",
    description: "What the handshake trace appendix means for migration evidence and auditor review.",
    category: "Convert",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Hybrid ML-KEM TLS handshake proof appendix.",
    excerpt: "What the handshake trace appendix means for migration evidence.",
    readiness: true,
  },
  {
    slug: "q-day-readiness-90-day-playbook",
    kind: "blog",
    markdownFile: "blog/q-day-readiness-90-day-playbook.md",
    title: "Q-Day readiness: a 90-day playbook for mid-market teams",
    description: "Quarter-by-quarter plan from inventory to Monitor — with evidence at each step.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "90-day Q-Day readiness playbook timeline.",
    excerpt: "A quarter-by-quarter plan from inventory to Monitor — with evidence at each step.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "how-encrypted-data-is-harvested",
    kind: "blog",
    markdownFile: "blog/how-encrypted-data-is-harvested.md",
    title: "How encrypted data is harvested (without breaking crypto today)",
    description: "Practitioner guide to HNDL collection vectors — breach, backups, cloud, and bulk capture.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-hndl-collection-vectors.svg",
    coverAlt: "Diagram of HNDL collection vectors.",
    excerpt: "How adversaries copy ciphertext today — without breaking RSA.",
    readiness: true,
    hndl: true,
    featured: true,
  },
  {
    slug: "hndl-myths-misconceptions",
    kind: "blog",
    markdownFile: "blog/hndl-myths-misconceptions.md",
    title: "HNDL myths: AES, TLS 1.3, and \"we'll rotate in 2035\"",
    description: "Common harvest-now-decrypt-later misconceptions for skeptical security teams.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "HNDL myths debunked.",
    excerpt: "Honest answers to the myths blocking HNDL inventory work.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "hndl-for-security-engineers",
    kind: "blog",
    markdownFile: "blog/hndl-for-security-engineers.md",
    title: "HNDL for security engineers: handshakes, archives, and evidence",
    description: "Technical HNDL primer — TLS records, hybrid migration, and auditor evidence.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-hndl-tls-handshake-flow.svg",
    coverAlt: "TLS handshake HNDL flow diagram.",
    excerpt: "Which protocol artifacts matter and what evidence to attach after migration.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "hndl-banking-shelf-life",
    kind: "blog",
    markdownFile: "blog/hndl-banking-shelf-life.md",
    title: "HNDL for banking: transaction archives and Mosca",
    description: "Financial data shelf-life and harvest-now-decrypt-later for regional banks.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-hndl-shelf-life-by-vertical.svg",
    coverAlt: "Banking data shelf-life chart.",
    excerpt: "When transaction archives make Mosca inequality hold today.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "hndl-gov-contractor-archives",
    kind: "blog",
    markdownFile: "blog/hndl-gov-contractor-archives.md",
    title: "HNDL for government contractors: CMMC and long-retention data",
    description: "HNDL exposure for defense contractors — NSM-10, CMMC, and archive shelf-life.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "Government contractor HNDL timeline.",
    excerpt: "CMMC evidence and Mosca scoring for long-retention contract data.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "qtangl-native-discovery-depth-2026",
    kind: "blog",
    markdownFile: "blog/qtangl-native-discovery-depth-2026.md",
    title: "Qtangl native discovery depth — host sensor + code/binary orchestration",
    description:
      "Unified Sensor fleet and OSS scanner pipeline into CBOM merge — partial gate G1/G2 with path to enterprise Yes.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "Qtangl discovery depth expansion diagram.",
    excerpt: "Host agents, code/binary OSS orchestration, and why evidence remains the moat.",
    readiness: true,
    featured: true,
  },
  {
    slug: "qtangl-full-stack-cpm-2026",
    kind: "blog",
    markdownFile: "blog/qtangl-full-stack-cpm-2026.md",
    title: "Qtangl full-stack cryptographic posture management",
    description:
      "Host sensor, code scan, and binary CBOM discovery ship as enterprise Yes — internally validated at scale.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Full-stack cryptographic posture management overview.",
    excerpt: "Discovery depth across host, code, and binary — one signed evidence pipeline.",
    readiness: true,
    featured: true,
  },
  {
    slug: "pqc-readiness-vendors-compared-2026",
    kind: "blog",
    markdownFile: "blog/pqc-readiness-vendors-compared-2026.md",
    title: "Post-quantum readiness vendors compared (2026)",
    description:
      "Landscape comparison of PQC readiness platforms — discovery methods, verifiable evidence, and mid-market fit.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "PQC vendor comparison landscape matrix.",
    excerpt: "Honest map of CPM vendors — and where signed verifiable evidence differentiates Qtangl.",
    readiness: true,
    featured: true,
    faq: [
      {
        question: "What is the main differentiator between PQC vendors in 2026?",
        answer:
          "Discovery and CBOM export are increasingly table stakes. Signed, publicly-verifiable evidence — reports auditors check offline — is Qtangl's standout capability in the landscape matrix.",
      },
      {
        question: "Where can I see the full comparison matrix?",
        answer: "The interactive hub lives at /compare with feature matrix, positioning map, and per-vendor pages.",
      },
    ],
  },
  {
    slug: "how-to-evaluate-pqc-readiness-platform",
    kind: "blog",
    markdownFile: "blog/how-to-evaluate-pqc-readiness-platform.md",
    title: "How to evaluate a PQC readiness platform",
    description: "RFP checklist for CISOs — discovery, evidence, drift, CBOM, and mid-market fit.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "PQC platform evaluation checklist.",
    excerpt: "RFP checklist to separate discovery theater from evidence auditors verify.",
    readiness: true,
    faq: [
      {
        question: "What should a PQC RFP require for evidence?",
        answer:
          "Require signed reports, public verify links, CBOM export, drift re-scan diff, and framework mapping — not dashboard-only proof.",
      },
    ],
  },
  {
    slug: "crypto-discovery-methods-compared",
    kind: "blog",
    markdownFile: "blog/crypto-discovery-methods-compared.md",
    title: "Crypto discovery methods compared",
    description: "Agentless vs host agents vs code scan vs KMS — why combine 2–3 methods.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Crypto discovery method comparison diagram.",
    excerpt: "Five discovery methods, their blind spots, and how vendors anchor to each.",
    readiness: true,
  },
  {
    slug: "what-is-cryptographic-posture-management",
    kind: "blog",
    markdownFile: "blog/what-is-cryptographic-posture-management.md",
    title: "What is Cryptographic Posture Management (CPM)?",
    description: "CPM defined — crypto-agility, CBOM, and how it differs from CLM and GRC.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "Cryptographic Posture Management category overview.",
    excerpt: "The 2026 label for post-quantum readiness — inventory, drift, and proven remediation.",
    readiness: true,
  },
  {
    slug: "harvest-now-decrypt-later-boards",
    kind: "blog",
    markdownFile: "blog/harvest-now-decrypt-later-boards.md",
    title: "Harvest-now-decrypt-later: what boards miss",
    description:
      "What boards miss about harvest-now-decrypt-later — Mosca inequality, HNDL exposure, and why quantum-vulnerable crypto needs inventory now.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "Timeline illustrating harvest-now-decrypt-later exposure before Q-Day.",
    excerpt: "HNDL exposure, Mosca inequality, and why inventory starts before Q-Day headlines.",
    readiness: true,
    hndl: true,
    faq: [
      {
        question: "Is my encryption broken today?",
        answer:
          "No. Quantum-vulnerable algorithms like RSA and ECDSA still protect data today. HNDL is about ciphertext captured now that may be decrypted after a future CRQC arrives.",
      },
      {
        question: "When will Q-Day happen?",
        answer:
          "No one knows the exact date. Google and Cloudflare accelerated internal readiness targets to 2029 as a planning signal — not a prediction. Migration takes years regardless of the exact timeline.",
      },
      {
        question: "What is the first step for a mid-market CISO?",
        answer:
          "Run a cryptographic inventory: which endpoints still depend on RSA or ECDSA, which third parties embed legacy crypto, and who owns remediation. A live scan beats a one-time spreadsheet exercise.",
      },
    ],
  },
  {
    slug: "video-companion-shors-algorithm-minutephysics",
    kind: "video-companion",
    markdownFile: "blog/video-companion-shors-algorithm-minutephysics.md",
    title: "After minutephysics on Shor's: what CISOs must know about RSA and ECC",
    description: "Original takeaways from minutephysics on Shor's algorithm — and how to map the threat to your PKI inventory.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/threat-map.png",
    coverAlt: "Diagram of quantum threat to RSA and ECC versus AES.",
    excerpt: "Shor's algorithm in plain language — plus what to inventory this quarter.",
    readiness: true,
    featured: true,
  },
  {
    slug: "video-companion-quantum-power-veritasium",
    kind: "video-companion",
    markdownFile: "blog/video-companion-quantum-power-veritasium.md",
    title: "After Veritasium: from Shor's threat to NIST PQC standards",
    description: "Veritasium connects quantum computing, HNDL, and NIST PQC — with migration steps for security teams.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/threat-map.png",
    coverAlt: "Post-quantum cryptography standards overview.",
    excerpt: "From Shor's to NIST FIPS — the full arc in one video companion.",
    readiness: true,
    featured: true,
  },
  {
    slug: "video-companion-pbs-shor-period-finding",
    kind: "video-companion",
    markdownFile: "blog/video-companion-pbs-shor-period-finding.md",
    title: "After PBS Infinite Series: period-finding and the quantum threat to PKI",
    description: "PBS goes deeper on Shor's number theory — takeaways for security engineers.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/threat-map.png",
    coverAlt: "Period-finding concept diagram for Shor's algorithm.",
    excerpt: "Period-finding without a math degree — and PKI inventory next steps.",
    readiness: true,
  },
  {
    slug: "video-companion-physics-world-shor",
    kind: "video-companion",
    markdownFile: "blog/video-companion-physics-world-shor.md",
    title: "Peter Shor in his own words: implications for your PKI",
    description: "Physics World interview with Peter Shor — factoring and future quantum computers.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/threat-map.png",
    coverAlt: "Peter Shor algorithm implications for PKI.",
    excerpt: "Hear Shor explain the algorithm — then inventory your certificates.",
    readiness: true,
  },
  {
    slug: "video-companion-dustin-moody-nist-strategy",
    kind: "video-companion",
    markdownFile: "blog/video-companion-dustin-moody-nist-strategy.md",
    title: "After NIST's Dustin Moody: your 12-month post-quantum strategy",
    description: "NIST PQC lead on 2035 timelines, migration myths, and crypto-agility.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "NIST post-quantum migration timeline.",
    excerpt: "Dustin Moody's 12-month playbook for enterprise PQC migration.",
    readiness: true,
    featured: true,
  },
  {
    slug: "video-companion-nist-pqc-update-rwpqc-2026",
    kind: "video-companion",
    markdownFile: "blog/video-companion-nist-pqc-update-rwpqc-2026.md",
    title: "After RWPQC 2026: FIPS status, Falcon, HQC, and the 2035 timeline",
    description: "RWPQC session on FIPS 203–205, on-ramp signatures, and global roadmaps.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "NIST PQC standards update diagram.",
    excerpt: "FIPS status, backup algorithms, and 2035 deprecation tiers.",
    readiness: true,
  },
  {
    slug: "video-companion-mosca-intel-quantum-security",
    kind: "video-companion",
    markdownFile: "blog/video-companion-mosca-intel-quantum-security.md",
    title: "After Michele Mosca: Mosca inequality for your board",
    description: "Michele Mosca on quantum threats, crypto-agility, and multi-year migration.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/mosca-gauge.png",
    coverAlt: "Mosca inequality X plus Y versus Z gauge.",
    excerpt: "Mosca inequality for executives — with board-ready framing.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "video-companion-root-causes-moody-pqc",
    kind: "video-companion",
    markdownFile: "blog/video-companion-root-causes-moody-pqc.md",
    title: "After Root Causes + Dustin Moody: on-ramp signatures and backup algorithms",
    description: "Root Causes 613 on NIST PQC contests, Falcon, HQC, and on-ramp signatures.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "NIST PQC on-ramp signature competition overview.",
    excerpt: "Why NIST keeps standardizing after FIPS 203–205.",
    readiness: true,
  },
  {
    slug: "video-companion-cloudflare-pq-roadmap",
    kind: "video-companion",
    markdownFile: "blog/video-companion-cloudflare-pq-roadmap.md",
    title: "Cloudflare's 2029 PQ roadmap: what enterprises should copy",
    description: "Cloudflare accelerated PQ targets — encryption, authentication, and hybrid TLS lessons.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/hybrid-tls-handshake.png",
    coverAlt: "Hybrid TLS post-quantum handshake diagram.",
    excerpt: "What Cloudflare's 2029 roadmap means for your program.",
    readiness: true,
  },
  {
    slug: "video-companion-cisa-quantum-readiness",
    kind: "video-companion",
    markdownFile: "blog/video-companion-cisa-quantum-readiness.md",
    title: "After CISA: federal PQC migration playbook for private sector",
    description: "CISA quantum readiness — HNDL, hybrid migration, and discovery automation.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "CISA post-quantum migration playbook.",
    excerpt: "CISA guidance translated for mid-market security teams.",
    readiness: true,
  },
  {
    slug: "video-companion-kyber-dilithium-menezes",
    kind: "video-companion",
    markdownFile: "blog/video-companion-kyber-dilithium-menezes.md",
    title: "After Alfred Menezes: ML-KEM and ML-DSA in plain language",
    description: "Cryptography 101 course on Kyber and Dilithium — FIPS 203 and 204.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/nist-algorithm-tree.png",
    coverAlt: "NIST ML-KEM and ML-DSA algorithm tree.",
    excerpt: "Lattice KEM and signatures from Alfred Menezes' course.",
    readiness: true,
  },
  {
    slug: "video-companion-open-quantum-safe-liboqs",
    kind: "video-companion",
    markdownFile: "blog/video-companion-open-quantum-safe-liboqs.md",
    title: "Hands-on with Open Quantum Safe: your first ML-KEM keypair",
    description: "liboqs and IBM quantum-safe OpenSSL — prototype PQC before production.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Open Quantum Safe liboqs hands-on guide.",
    excerpt: "Prototype ML-KEM with liboqs — and know production limits.",
    readiness: true,
  },
  {
    slug: "shors-algorithm-explained-for-cisos",
    kind: "blog",
    markdownFile: "blog/shors-algorithm-explained-for-cisos.md",
    title: "Shor's algorithm for CISOs (no math degree required)",
    description: "Executive Shor's explainer — RSA/ECC risk, AES survival, and first inventory steps.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/threat-map.png",
    coverAlt: "Shor's algorithm threat map for CISOs.",
    excerpt: "Shor's without the math degree — for security leaders.",
    readiness: true,
    featured: true,
  },
  {
    slug: "grovers-algorithm-and-aes",
    kind: "blog",
    markdownFile: "blog/grovers-algorithm-and-aes.md",
    title: "Grover's algorithm and AES: why symmetric crypto mostly survives",
    description: "Grover weakens AES — unlike Shor, the fix is larger keys.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/threat-map.png",
    coverAlt: "Grover's algorithm impact on AES key sizes.",
    excerpt: "Why AES mostly survives — and why PKI migration still comes first.",
    readiness: true,
  },
  {
    slug: "qkd-vs-post-quantum-cryptography",
    kind: "blog",
    markdownFile: "blog/qkd-vs-post-quantum-cryptography.md",
    title: "QKD vs PQC: what security teams confuse",
    description: "Quantum key distribution vs post-quantum cryptography — different problems, different deployments.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/qkd-vs-pqc.png",
    coverAlt: "QKD versus PQC comparison diagram.",
    excerpt: "QKD is not a substitute for TLS migration — here's why.",
    readiness: true,
  },
  {
    slug: "mosca-inequality-worked-examples",
    kind: "blog",
    markdownFile: "blog/mosca-inequality-worked-examples.md",
    title: "Mosca inequality worked examples by industry",
    description: "X + Y > Z for healthcare, banking, and SaaS — when HNDL exposure is already open.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/mosca-gauge.png",
    coverAlt: "Mosca inequality worked examples chart.",
    excerpt: "Industry examples for Mosca's X + Y > Z inequality.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "nist-fips-203-204-205-primer",
    kind: "blog",
    markdownFile: "blog/nist-fips-203-204-205-primer.md",
    title: "FIPS 203, 204, and 205 in plain language",
    description: "ML-KEM, ML-DSA, and SLH-DSA — what NIST standardized and what each replaces.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/nist-algorithm-tree.png",
    coverAlt: "FIPS 203 204 205 algorithm primer diagram.",
    excerpt: "ML-KEM, ML-DSA, SLH-DSA — the NIST trio in plain language.",
    readiness: true,
    featured: true,
  },
  {
    slug: "hybrid-tls-migration-guide",
    kind: "blog",
    markdownFile: "blog/hybrid-tls-migration-guide.md",
    title: "Hybrid TLS migration: X25519 + ML-KEM in practice",
    description: "Hybrid post-quantum TLS — deployment path, lab setup, and audit evidence.",
    category: "Convert",
    coverImage: "/learn/diagrams/hybrid-tls-handshake.png",
    coverAlt: "Hybrid TLS X25519 ML-KEM handshake diagram.",
    excerpt: "Deploy hybrid ML-KEM TLS — lab to production with evidence.",
    readiness: true,
  },
  {
    slug: "hndl-collection-vectors-deep-dive",
    kind: "blog",
    markdownFile: "blog/hndl-collection-vectors-deep-dive.md",
    title: "HNDL collection vectors: breach, backups, and TLS capture",
    description: "How ciphertext is harvested today — threat model and prioritization.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/hndl-timeline.png",
    coverAlt: "HNDL collection vectors timeline diagram.",
    excerpt: "Breaches, backups, TLS — where HNDL collection happens.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "crypto-attack-surface-map",
    kind: "blog",
    markdownFile: "blog/crypto-attack-surface-map.md",
    title: "Where cryptography hides: an attack surface map for PQC migration",
    description: "TLS is the tip of the iceberg — JWKS, SSH, email, firmware, and tokens.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/crypto-attack-surface.png",
    coverAlt: "Cryptographic attack surface map diagram.",
    excerpt: "Map every place quantum-vulnerable crypto hides in your estate.",
    readiness: true,
  },
  {
    slug: "pqc-migration-phases-explained",
    kind: "blog",
    markdownFile: "blog/pqc-migration-phases-explained.md",
    title: "PQC migration phases: discover, prioritize, hybrid, verify",
    description: "Phased migration aligned to NIST IR 8547, CNSA 2.0, and NSM-10.",
    category: "Q-Day readiness",
    coverImage: "/learn/diagrams/migration-stack.png",
    coverAlt: "PQC migration phases stack diagram.",
    excerpt: "Discover → prioritize → hybrid → verify — the migration program model.",
    readiness: true,
  },
  {
    slug: "learning-quantum-crypto-4-week-path",
    kind: "blog",
    markdownFile: "blog/learning-quantum-crypto-4-week-path.md",
    title: "Learn quantum cryptography in 4 weeks: video + reading path",
    description: "Structured curriculum with embedded videos, NIST links, and blog companions.",
    category: "Q-Day readiness",
    coverImage: "/learn/topics/quantum-crypto-foundations.png",
    coverAlt: "Four-week quantum cryptography learning path.",
    excerpt: "The full 4-week video and reading curriculum — on-site index.",
    readiness: true,
    featured: true,
  },
] as const;

export const readinessFrameworkRegistry: readonly ReadinessFrameworkRegistryEntry[] = [
  { slug: "nsm-10", markdownFile: "frameworks/nsm-10.md", externalSourceIds: ["nsm-10", "nsa-cnsa-2", "nist-ir-8547"] },
  { slug: "cmmc", markdownFile: "frameworks/cmmc.md", externalSourceIds: ["nsm-10", "nist-ir-8547", "palo-alto-q-day"] },
  { slug: "pci-dss-4", markdownFile: "frameworks/pci-dss-4.md", externalSourceIds: ["nist-ir-8547", "fips-203"] },
  { slug: "ml-kem", markdownFile: "frameworks/ml-kem.md", externalSourceIds: ["fips-203", "fips-204", "fips-205", "nist-pqc-overview"] },
  { slug: "nist-ir-8547", markdownFile: "frameworks/nist-ir-8547.md", externalSourceIds: ["nist-ir-8547", "nist-pqc-overview"] },
  { slug: "cnsa-2.0", markdownFile: "frameworks/cnsa-2.0.md", externalSourceIds: ["nsa-cnsa-2", "nsm-10"] },
  { slug: "hipaa-hndl", markdownFile: "frameworks/hipaa-hndl.md", externalSourceIds: ["nist-pqc-overview", "palo-alto-q-day", "nist-ir-8547"] },
  { slug: "banking-hndl", markdownFile: "frameworks/banking-hndl.md", externalSourceIds: ["nist-pqc-overview", "nist-ir-8547", "mosca-inequality"] },
  { slug: "gov-hndl", markdownFile: "frameworks/gov-hndl.md", externalSourceIds: ["nsm-10", "nsa-cnsa-2", "nist-ir-8547", "mosca-inequality"] },
  { slug: "eu-cra", markdownFile: "frameworks/eu-cra.md", externalSourceIds: ["nist-pqc-overview", "nist-ir-8547"] },
] as const;

export function getReadinessBlogEntry(slug: string): ReadinessBlogRegistryEntry | undefined {
  return readinessBlogRegistry.find((entry) => entry.slug === slug);
}

export function getReadinessFrameworkMarkdownEntry(
  slug: string,
): ReadinessFrameworkRegistryEntry | undefined {
  return readinessFrameworkRegistry.find((entry) => entry.slug === slug);
}

export const readinessBlogSlugs = readinessBlogRegistry.map((entry) => entry.slug);

export function readinessBlogPostsForIndex() {
  return readinessBlogRegistry.map((entry) => ({
    slug: entry.slug,
    href: `/blog/${entry.slug}`,
    category: entry.category,
    coverImage: entry.coverImage,
    coverAlt: entry.coverAlt,
    title: entry.title,
    excerpt: entry.excerpt,
    description: entry.description,
    readiness: true as const,
    ...(entry.hndl ? { hndl: true as const } : {}),
    ...(entry.featured ? { featured: true as const } : {}),
  }));
}
