import type {
  ReadinessBlogRegistryEntry,
  ReadinessFrameworkRegistryEntry,
} from "@/lib/readiness-content-types";

export const readinessBlogRegistry: readonly ReadinessBlogRegistryEntry[] = [
  {
    slug: "video-companion-q-day-explained",
    kind: "video-companion",
    markdownFile: "blog/video-companion-q-day-explained.md",
    title: "After Q-Day Explained: what mid-market CISOs should do this quarter",
    description: "Original takeaways from a popular Q-Day video — CRQC timelines, HNDL exposure, and inventory steps.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "Q-Day timeline illustrating post-quantum cryptography risk.",
    excerpt: "Original takeaways from a popular Q-Day explainer — plus what to do this quarter.",
    readiness: true,
  },
  {
    slug: "video-companion-hndl-jeremy-allison",
    kind: "video-companion",
    markdownFile: "blog/video-companion-hndl-jeremy-allison.md",
    title: "After Jeremy Allison on HNDL: what your security team should do now",
    description: "Practitioner insights on harvest-now-decrypt-later and how to quantify exposure before Q-Day headlines.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "Harvest-now-decrypt-later exposure timeline.",
    excerpt: "Practitioner insights on HNDL — and how to inventory before migration finishes.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "video-companion-pq-algorithms-nist",
    kind: "video-companion",
    markdownFile: "blog/video-companion-pq-algorithms-nist.md",
    title: "After the NIST PQC algorithms video: your ML-KEM migration checklist",
    description: "ML-KEM, ML-DSA, and SLH-DSA in plain language — with hybrid TLS as the near-term path.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Post-quantum algorithm standards overview.",
    excerpt: "ML-KEM, ML-DSA, and SLH-DSA in plain language — with a migration checklist.",
    readiness: true,
  },
  {
    slug: "spreadsheet-crypto-inventory-wrong",
    kind: "blog",
    markdownFile: "blog/spreadsheet-crypto-inventory-wrong.md",
    title: "Why your spreadsheet crypto inventory is wrong",
    description: "Manual TLS inventories miss drift, JWKS, STARTTLS, and re-scan verification.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Spreadsheet versus live cryptographic inventory comparison.",
    excerpt: "Manual TLS inventories miss drift, JWKS, and STARTTLS — why spreadsheets fail.",
    readiness: true,
  },
  {
    slug: "reading-qtangl-cbom-export",
    kind: "blog",
    markdownFile: "blog/reading-qtangl-cbom-export.md",
    title: "Reading a Qtangl CBOM export: field-by-field guide",
    description: "Walk through a sample CycloneDX Crypto Bill of Materials — algorithms, assets, and GRC integration.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "CycloneDX CBOM export fields and remediation mapping.",
    excerpt: "Walk through a sample CBOM JSON — algorithms, assets, and GRC integration.",
    readiness: true,
  },
  {
    slug: "mosca-inequality-for-cisos",
    kind: "blog",
    markdownFile: "blog/mosca-inequality-for-cisos.md",
    title: "Mosca inequality explained for CISOs",
    description: "Turn Mosca's X + Y > Z into a board-ready planning question for HNDL exposure.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "Mosca inequality X plus Y greater than Z diagram.",
    excerpt: "Turn Mosca's X + Y > Z into a board-ready planning question.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "cmmc-crypto-inventory-evidence",
    kind: "blog",
    markdownFile: "blog/cmmc-crypto-inventory-evidence.md",
    title: "CMMC crypto controls: inventory evidence auditors want",
    description: "What CMMC Level 2 assessors expect — inventory artifacts, not slide decks.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "CMMC Level 2 cryptographic inventory evidence checklist.",
    excerpt: "What CMMC assessors expect — inventory artifacts, not slide decks.",
    readiness: true,
  },
  {
    slug: "crypto-drift-one-scan-not-enough",
    kind: "blog",
    markdownFile: "blog/crypto-drift-one-scan-not-enough.md",
    title: "Crypto drift: why one scan is not enough",
    description: "A baseline scan satisfies this quarter's board slide — it does not catch next week's deployment.",
    category: "Monitor",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Crypto drift diff between consecutive scans.",
    excerpt: "Why a baseline scan decays — and how Monitor catches regression.",
    readiness: true,
  },
  {
    slug: "q-day-monitor-alerts-setup",
    kind: "blog",
    markdownFile: "blog/q-day-monitor-alerts-setup.md",
    title: "Setting up Q-Day Monitor alerts",
    description: "Configure re-scan cadence, drift alerts, and readiness score trends.",
    category: "Monitor",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Monitor alert configuration for crypto drift.",
    excerpt: "Configure re-scan cadence, drift alerts, and readiness score trends.",
    readiness: true,
  },
  {
    slug: "remediation-backlog-deadline-prioritization",
    kind: "blog",
    markdownFile: "blog/remediation-backlog-deadline-prioritization.md",
    title: "Remediation backlog prioritization by deadline tier",
    description: "Prioritize PQC fixes by NSM-10, CNSA 2.0, and data shelf-life — not gut feel.",
    category: "Convert",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "Remediation backlog prioritized by compliance deadline tier.",
    excerpt: "Prioritize fixes by NSM-10, CNSA 2.0, and data shelf-life.",
    readiness: true,
  },
  {
    slug: "hybrid-tls-handshake-appendix",
    kind: "blog",
    markdownFile: "blog/hybrid-tls-handshake-appendix.md",
    title: "Hybrid TLS proof: what the handshake appendix means",
    description: "What the handshake trace appendix means for migration evidence and auditor review.",
    category: "Convert",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Hybrid ML-KEM TLS handshake proof appendix.",
    excerpt: "What the handshake trace appendix means for migration evidence.",
    readiness: true,
  },
  {
    slug: "q-day-readiness-90-day-playbook",
    kind: "blog",
    markdownFile: "blog/q-day-readiness-90-day-playbook.md",
    title: "Q-Day readiness: a 90-day playbook for mid-market teams",
    description: "Quarter-by-quarter plan from inventory to Monitor — with evidence at each step.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "90-day Q-Day readiness playbook timeline.",
    excerpt: "A quarter-by-quarter plan from inventory to Monitor — with evidence at each step.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "how-encrypted-data-is-harvested",
    kind: "blog",
    markdownFile: "blog/how-encrypted-data-is-harvested.md",
    title: "How encrypted data is harvested (without breaking crypto today)",
    description: "Practitioner guide to HNDL collection vectors — breach, backups, cloud, and bulk capture.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-hndl-collection-vectors.svg",
    coverAlt: "Diagram of HNDL collection vectors.",
    excerpt: "How adversaries copy ciphertext today — without breaking RSA.",
    readiness: true,
    hndl: true,
    featured: true,
  },
  {
    slug: "hndl-myths-misconceptions",
    kind: "blog",
    markdownFile: "blog/hndl-myths-misconceptions.md",
    title: "HNDL myths: AES, TLS 1.3, and \"we'll rotate in 2035\"",
    description: "Common harvest-now-decrypt-later misconceptions for skeptical security teams.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "HNDL myths debunked.",
    excerpt: "Honest answers to the myths blocking HNDL inventory work.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "hndl-for-security-engineers",
    kind: "blog",
    markdownFile: "blog/hndl-for-security-engineers.md",
    title: "HNDL for security engineers: handshakes, archives, and evidence",
    description: "Technical HNDL primer — TLS records, hybrid migration, and auditor evidence.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-hndl-tls-handshake-flow.svg",
    coverAlt: "TLS handshake HNDL flow diagram.",
    excerpt: "Which protocol artifacts matter and what evidence to attach after migration.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "hndl-banking-shelf-life",
    kind: "blog",
    markdownFile: "blog/hndl-banking-shelf-life.md",
    title: "HNDL for banking: transaction archives and Mosca",
    description: "Financial data shelf-life and harvest-now-decrypt-later for regional banks.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-hndl-shelf-life-by-vertical.svg",
    coverAlt: "Banking data shelf-life chart.",
    excerpt: "When transaction archives make Mosca inequality hold today.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "hndl-gov-contractor-archives",
    kind: "blog",
    markdownFile: "blog/hndl-gov-contractor-archives.md",
    title: "HNDL for government contractors: CMMC and long-retention data",
    description: "HNDL exposure for defense contractors — NSM-10, CMMC, and archive shelf-life.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "Government contractor HNDL timeline.",
    excerpt: "CMMC evidence and Mosca scoring for long-retention contract data.",
    readiness: true,
    hndl: true,
  },
  {
    slug: "qtangl-native-discovery-depth-2026",
    kind: "blog",
    markdownFile: "blog/qtangl-native-discovery-depth-2026.md",
    title: "Qtangl native discovery depth — host sensor + code/binary orchestration",
    description:
      "Unified Sensor fleet and OSS scanner pipeline into CBOM merge — partial gate G1/G2 with path to enterprise Yes.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "Qtangl discovery depth expansion diagram.",
    excerpt: "Host agents, code/binary OSS orchestration, and why evidence remains the moat.",
    readiness: true,
    featured: true,
  },
  {
    slug: "qtangl-full-stack-cpm-2026",
    kind: "blog",
    markdownFile: "blog/qtangl-full-stack-cpm-2026.md",
    title: "Qtangl full-stack cryptographic posture management",
    description:
      "Host sensor, code scan, and binary CBOM discovery ship as enterprise Yes — internally validated at scale.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Full-stack cryptographic posture management overview.",
    excerpt: "Discovery depth across host, code, and binary — one signed evidence pipeline.",
    readiness: true,
    featured: true,
  },
  {
    slug: "pqc-readiness-vendors-compared-2026",
    kind: "blog",
    markdownFile: "blog/pqc-readiness-vendors-compared-2026.md",
    title: "Post-quantum readiness vendors compared (2026)",
    description:
      "Landscape comparison of PQC readiness platforms — discovery methods, verifiable evidence, and mid-market fit.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "PQC vendor comparison landscape matrix.",
    excerpt: "Honest map of CPM vendors — and where signed verifiable evidence differentiates Qtangl.",
    readiness: true,
    featured: true,
    faq: [
      {
        question: "What is the main differentiator between PQC vendors in 2026?",
        answer:
          "Discovery and CBOM export are increasingly table stakes. Signed, publicly-verifiable evidence — reports auditors check offline — is Qtangl's standout capability in the landscape matrix.",
      },
      {
        question: "Where can I see the full comparison matrix?",
        answer: "The interactive hub lives at /compare with feature matrix, positioning map, and per-vendor pages.",
      },
    ],
  },
  {
    slug: "how-to-evaluate-pqc-readiness-platform",
    kind: "blog",
    markdownFile: "blog/how-to-evaluate-pqc-readiness-platform.md",
    title: "How to evaluate a PQC readiness platform",
    description: "RFP checklist for CISOs — discovery, evidence, drift, CBOM, and mid-market fit.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "PQC platform evaluation checklist.",
    excerpt: "RFP checklist to separate discovery theater from evidence auditors verify.",
    readiness: true,
    faq: [
      {
        question: "What should a PQC RFP require for evidence?",
        answer:
          "Require signed reports, public verify links, CBOM export, drift re-scan diff, and framework mapping — not dashboard-only proof.",
      },
    ],
  },
  {
    slug: "crypto-discovery-methods-compared",
    kind: "blog",
    markdownFile: "blog/crypto-discovery-methods-compared.md",
    title: "Crypto discovery methods compared",
    description: "Agentless vs host agents vs code scan vs KMS — why combine 2–3 methods.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-scanner-cover.svg",
    coverAlt: "Crypto discovery method comparison diagram.",
    excerpt: "Five discovery methods, their blind spots, and how vendors anchor to each.",
    readiness: true,
  },
  {
    slug: "what-is-cryptographic-posture-management",
    kind: "blog",
    markdownFile: "blog/what-is-cryptographic-posture-management.md",
    title: "What is Cryptographic Posture Management (CPM)?",
    description: "CPM defined — crypto-agility, CBOM, and how it differs from CLM and GRC.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-deadlines-cover.svg",
    coverAlt: "Cryptographic Posture Management category overview.",
    excerpt: "The 2026 label for post-quantum readiness — inventory, drift, and proven remediation.",
    readiness: true,
  },
  {
    slug: "harvest-now-decrypt-later-boards",
    kind: "blog",
    markdownFile: "blog/harvest-now-decrypt-later-boards.md",
    title: "Harvest-now-decrypt-later: what boards miss",
    description:
      "What boards miss about harvest-now-decrypt-later — Mosca inequality, HNDL exposure, and why quantum-vulnerable crypto needs inventory now.",
    category: "Q-Day readiness",
    coverImage: "/qtangl-pqc-hndl-cover.svg",
    coverAlt: "Timeline illustrating harvest-now-decrypt-later exposure before Q-Day.",
    excerpt: "HNDL exposure, Mosca inequality, and why inventory starts before Q-Day headlines.",
    readiness: true,
    hndl: true,
    faq: [
      {
        question: "Is my encryption broken today?",
        answer:
          "No. Quantum-vulnerable algorithms like RSA and ECDSA still protect data today. HNDL is about ciphertext captured now that may be decrypted after a future CRQC arrives.",
      },
      {
        question: "When will Q-Day happen?",
        answer:
          "No one knows the exact date. Google and Cloudflare accelerated internal readiness targets to 2029 as a planning signal — not a prediction. Migration takes years regardless of the exact timeline.",
      },
      {
        question: "What is the first step for a mid-market CISO?",
        answer:
          "Run a cryptographic inventory: which endpoints still depend on RSA or ECDSA, which third parties embed legacy crypto, and who owns remediation. A live scan beats a one-time spreadsheet exercise.",
      },
    ],
  },
] as const;

export const readinessFrameworkRegistry: readonly ReadinessFrameworkRegistryEntry[] = [
  { slug: "nsm-10", markdownFile: "frameworks/nsm-10.md", externalSourceIds: ["nsm-10", "nsa-cnsa-2", "nist-ir-8547"] },
  { slug: "cmmc", markdownFile: "frameworks/cmmc.md", externalSourceIds: ["nsm-10", "nist-ir-8547", "palo-alto-q-day"] },
  { slug: "pci-dss-4", markdownFile: "frameworks/pci-dss-4.md", externalSourceIds: ["nist-ir-8547", "fips-203"] },
  { slug: "ml-kem", markdownFile: "frameworks/ml-kem.md", externalSourceIds: ["fips-203", "fips-204", "fips-205", "nist-pqc-overview"] },
  { slug: "nist-ir-8547", markdownFile: "frameworks/nist-ir-8547.md", externalSourceIds: ["nist-ir-8547", "nist-pqc-overview"] },
  { slug: "cnsa-2.0", markdownFile: "frameworks/cnsa-2.0.md", externalSourceIds: ["nsa-cnsa-2", "nsm-10"] },
  { slug: "hipaa-hndl", markdownFile: "frameworks/hipaa-hndl.md", externalSourceIds: ["nist-pqc-overview", "palo-alto-q-day", "nist-ir-8547"] },
  { slug: "banking-hndl", markdownFile: "frameworks/banking-hndl.md", externalSourceIds: ["nist-pqc-overview", "nist-ir-8547", "mosca-inequality"] },
  { slug: "gov-hndl", markdownFile: "frameworks/gov-hndl.md", externalSourceIds: ["nsm-10", "nsa-cnsa-2", "nist-ir-8547", "mosca-inequality"] },
  { slug: "eu-cra", markdownFile: "frameworks/eu-cra.md", externalSourceIds: ["nist-pqc-overview", "nist-ir-8547"] },
] as const;

export function getReadinessBlogEntry(slug: string): ReadinessBlogRegistryEntry | undefined {
  return readinessBlogRegistry.find((entry) => entry.slug === slug);
}

export function getReadinessFrameworkMarkdownEntry(
  slug: string,
): ReadinessFrameworkRegistryEntry | undefined {
  return readinessFrameworkRegistry.find((entry) => entry.slug === slug);
}

export const readinessBlogSlugs = readinessBlogRegistry.map((entry) => entry.slug);

export function readinessBlogPostsForIndex() {
  return readinessBlogRegistry.map((entry) => ({
    slug: entry.slug,
    href: `/blog/${entry.slug}`,
    category: entry.category,
    coverImage: entry.coverImage,
    coverAlt: entry.coverAlt,
    title: entry.title,
    excerpt: entry.excerpt,
    description: entry.description,
    readiness: true as const,
    ...(entry.hndl ? { hndl: true as const } : {}),
    ...(entry.featured ? { featured: true as const } : {}),
  }));
}
