import type { DocsEndpoint } from "@/lib/docs/types";
import { defineEndpoint, ROLE_ANY, ROLE_WRITE } from "@/lib/docs/endpoint-factory";

type HttpMethod = DocsEndpoint["method"];

function stub(
  id: string,
  method: HttpMethod,
  path: string,
  summary: string,
  auth = true,
  details: Pick<DocsEndpoint, "schemaUrl" | "role" | "notes" | "contentType"> = {},
): DocsEndpoint {
  return defineEndpoint(id, {
    method,
    path,
    status: "ga",
    summary,
    auth,
    role: method === "GET" ? ROLE_ANY : ROLE_WRITE,
    ...details,
    ...(details.schemaUrl ? { examples: [], tryIt: false } : {}),
  });
}

/** Routes documented for CI coverage; reference pages ship incrementally. */
export const platformExtendedEndpoints: Record<string, DocsEndpoint> = {
  "pqc-dogfood-latest": stub(
    "pqc-dogfood-latest",
    "GET",
    "/pqc/dogfood/latest",
    "Public latest Qtangl self-scan for the trust center dogfood tenant.",
    false,
  ),
  "pqc-dogfood-summary": stub(
    "pqc-dogfood-summary",
    "GET",
    "/pqc/dogfood/summary",
    "Public multi-domain dogfood posture summary with per-target freshness.",
    false,
  ),
  "pqc-dogfood-history": stub(
    "pqc-dogfood-history",
    "GET",
    "/pqc/dogfood/history",
    "Public readiness history for dogfood tenant scans (query: days=90).",
    false,
  ),
  "pqc-dogfood-auditor-bundle": stub(
    "pqc-dogfood-auditor-bundle",
    "GET",
    "/pqc/dogfood/auditor-bundle",
    "Quarterly auditor package metadata: verify URLs, board PDF links, transparency root.",
    false,
  ),
  "discovery-summary": stub(
    "discovery-summary",
    "GET",
    "/tenant/discovery/summary",
    "Discovery program summary: fleets, agents, jobs, and coverage counts.",
  ),
  "discovery-fleet-rotate-token": stub(
    "discovery-fleet-rotate-token",
    "POST",
    "/tenant/discovery/fleets/{fleet_id}/rotate-token",
    "Rotate fleet enrollment token and invalidate prior tokens.",
  ),
  "discovery-agents-revoke": stub(
    "discovery-agents-revoke",
    "POST",
    "/tenant/discovery/agents/revoke",
    "Revoke one or more host agent credentials.",
  ),
  "discovery-host-scan": stub(
    "discovery-host-scan",
    "POST",
    "/tenant/discovery/host-scan",
    "Trigger on-demand host sensor scan for enrolled agents.",
  ),
  "discovery-agent-enroll": stub(
    "discovery-agent-enroll",
    "POST",
    "/discovery/agent/enroll",
    "Enroll a host sensor with fleet enrollment token (mTLS in production).",
    false,
  ),
  "discovery-agent-heartbeat": stub(
    "discovery-agent-heartbeat",
    "POST",
    "/discovery/agent/heartbeat",
    "Agent heartbeat with version and capacity metadata.",
    false,
  ),
  "discovery-agent-findings": stub(
    "discovery-agent-findings",
    "POST",
    "/discovery/agent/findings",
    "Upload host discovery findings batch (discovery-finding-v1 schema).",
    false,
  ),
  "discovery-agent-update": stub(
    "discovery-agent-update",
    "GET",
    "/discovery/agent/update",
    "Check for sensor package updates (version manifest).",
    false,
  ),
  "discovery-host-drift": stub(
    "discovery-host-drift",
    "GET",
    "/tenant/discovery/host-drift",
    "Host-level crypto drift since prior discovery snapshot.",
  ),
  "discovery-code-targets-list": stub(
    "discovery-code-targets-list",
    "GET",
    "/tenant/discovery/code-targets",
    "List configured code scan targets (GitHub, GitLab, ADO).",
  ),
  "discovery-code-targets-create": stub(
    "discovery-code-targets-create",
    "POST",
    "/tenant/discovery/code-targets",
    "Register a repository or org for scheduled code scans.",
  ),
  "discovery-image-targets-list": stub(
    "discovery-image-targets-list",
    "GET",
    "/tenant/discovery/image-targets",
    "List container image scan targets.",
  ),
  "discovery-image-targets-create": stub(
    "discovery-image-targets-create",
    "POST",
    "/tenant/discovery/image-targets",
    "Register an OCI image reference for binary CBOM scans.",
  ),
  "discovery-github-webhook": stub(
    "discovery-github-webhook",
    "POST",
    "/tenant/discovery/github-webhook",
    "GitHub App webhook receiver for PR and push code scan events.",
    false,
  ),
  "discovery-gitlab-webhook": stub(
    "discovery-gitlab-webhook",
    "POST",
    "/tenant/discovery/gitlab-webhook",
    "GitLab webhook receiver for merge request code scan events.",
    false,
  ),
  "discovery-ado-webhook": stub(
    "discovery-ado-webhook",
    "POST",
    "/tenant/discovery/ado-webhook",
    "Azure DevOps webhook receiver for pipeline code scan events.",
    false,
  ),
  "discovery-pr-comment": stub(
    "discovery-pr-comment",
    "POST",
    "/tenant/discovery/pr-comment",
    "Post or update PR comment with code scan summary.",
  ),
  "discovery-offline-upload": stub(
    "discovery-offline-upload",
    "POST",
    "/tenant/discovery/offline-upload",
    "Upload offline sensor bundle or air-gapped findings export.",
  ),
  "discovery-github-app-install": stub(
    "discovery-github-app-install",
    "GET",
    "/tenant/discovery/github-app/install",
    "Begin GitHub App installation OAuth flow.",
  ),
  "discovery-github-app-callback": stub(
    "discovery-github-app-callback",
    "POST",
    "/tenant/discovery/github-app/callback",
    "Complete GitHub App installation and store credentials.",
  ),
  "discovery-source-runtime-diff": stub(
    "discovery-source-runtime-diff",
    "POST",
    "/tenant/discovery/source-runtime-diff",
    "Compare code scan findings vs live TLS/host inventory for a scope.",
  ),
  "drift-summary": stub(
    "drift-summary",
    "GET",
    "/tenant/drift/summary",
    "Tenant-wide drift summary across sources and scopes.",
  ),
  "drift-scope": stub(
    "drift-scope",
    "GET",
    "/tenant/drift/{source_type}/{scope_key}",
    "Latest drift delta for a source type and scope key.",
  ),
  "drift-history": stub(
    "drift-history",
    "GET",
    "/tenant/drift/history",
    "Historical drift events for analytics and audit.",
  ),
  "remediation-program-list": stub(
    "remediation-program-list",
    "GET",
    "/tenant/remediation/program",
    "List remediation program items with priority and status.",
  ),
  "remediation-program-create": stub(
    "remediation-program-create",
    "POST",
    "/tenant/remediation/program",
    "Create or bulk-import remediation program items.",
  ),
  "remediation-program-velocity": stub(
    "remediation-program-velocity",
    "GET",
    "/tenant/remediation/program/velocity",
    "Remediation velocity metrics for executive reporting.",
  ),
  "remediation-program-simulate": stub(
    "remediation-program-simulate",
    "POST",
    "/tenant/remediation/program/simulate",
    "Simulate remediation outcomes without applying changes.",
  ),
  "remediation-program-migrate-legacy": stub(
    "remediation-program-migrate-legacy",
    "POST",
    "/tenant/remediation/program/migrate-legacy",
    "Migrate legacy remediation backlog into program items.",
  ),
  "remediation-program-update": stub(
    "remediation-program-update",
    "PUT",
    "/tenant/remediation/program/{item_id}",
    "Update remediation program item fields and ownership.",
  ),
  "remediation-program-recommendations": stub(
    "remediation-program-recommendations",
    "GET",
    "/tenant/remediation/program/recommendations",
    "ML-assisted remediation recommendations for open items.",
  ),
  "remediation-program-playbook": stub(
    "remediation-program-playbook",
    "GET",
    "/tenant/remediation/program/{item_id}/playbook",
    "Fetch playbook steps for a program item.",
  ),
  "remediation-program-verify": stub(
    "remediation-program-verify",
    "POST",
    "/tenant/remediation/program/{item_id}/verify",
    "Re-scan and verify remediation for a program item.",
  ),
  "remediation-flip-dry-run": stub(
    "remediation-flip-dry-run",
    "POST",
    "/tenant/remediation/program/{program_item_id}/flip/dry-run",
    "Simulate crypto flip overlay without applying production changes.",
  ),
  "remediation-flip-execute": stub(
    "remediation-flip-execute",
    "POST",
    "/tenant/remediation/program/{program_item_id}/flip",
    "Execute orchestrated crypto flip for a program item.",
  ),
  "crypto-flips-list": stub(
    "crypto-flips-list",
    "GET",
    "/tenant/flips",
    "List crypto flip jobs with status and approval state.",
  ),
  "crypto-flips-get": stub(
    "crypto-flips-get",
    "GET",
    "/tenant/flips/{job_id}",
    "Fetch crypto flip job detail and audit trail.",
  ),
  "crypto-flips-approve": stub(
    "crypto-flips-approve",
    "POST",
    "/tenant/flips/{job_id}/approve",
    "Approve a pending crypto flip job (dual-control when configured).",
  ),
  "crypto-flips-cancel": stub(
    "crypto-flips-cancel",
    "POST",
    "/tenant/flips/{job_id}/cancel",
    "Cancel an in-flight or pending crypto flip job.",
  ),
  "crypto-flips-retry": stub(
    "crypto-flips-retry",
    "POST",
    "/tenant/flips/{job_id}/retry",
    "Retry a failed crypto flip job step.",
  ),
  "crypto-flips-poll": stub(
    "crypto-flips-poll",
    "GET",
    "/tenant/flips/{job_id}/poll",
    "Poll flip job progress until terminal state.",
  ),
  "tenant-integrations-jira-webhook": stub(
    "tenant-integrations-jira-webhook",
    "POST",
    "/integrations/jira/webhook",
    "Synchronize a linked Jira issue status through an authenticated custom JSON relay.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/integrations/jira_webhook_integrations_jira_webhook_post",
      role: "operator | admin",
      notes: ["Requires tenant API/session credentials. Native Jira signature validation is not supported. Tenant hints must match the authenticated tenant, and the issue key must match its stored Jira link."],
    },
  ),
  "tenant-scans-scan-id-graph-get": stub(
    "tenant-scans-scan-id-graph-get",
    "GET",
    "/tenant/scans/{scan_id}/graph",
    "Inspect algorithm, certificate, and asset relationships from one tenant-owned scan.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_scan_graph_tenant_scans__scan_id__graph_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-hndl-exposure-get": stub(
    "tenant-hndl-exposure-get",
    "GET",
    "/tenant/hndl/exposure",
    "Estimate harvest-now-decrypt-later exposure using inventory and retention assumptions.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_hndl_exposure_tenant_hndl_exposure_get",
      role: "viewer | operator | admin",
      notes: ["Planning heuristics and scenario ranges are illustrative, not calibrated confidence intervals or Q-Day predictions. They do not prove that remediation has occurred."],
    },
  ),
  "tenant-findings-finding-id-comments-get": stub(
    "tenant-findings-finding-id-comments-get",
    "GET",
    "/tenant/findings/{finding_id}/comments",
    "Read or maintain tenant finding discussion comments.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_finding_comments_list_tenant_findings__finding_id__comments_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-findings-finding-id-comments-post": stub(
    "tenant-findings-finding-id-comments-post",
    "POST",
    "/tenant/findings/{finding_id}/comments",
    "Read or maintain tenant finding discussion comments.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_finding_comments_create_tenant_findings__finding_id__comments_post",
      role: "operator | admin",
    },
  ),
  "tenant-findings-finding-id-comments-comment-id-delete": stub(
    "tenant-findings-finding-id-comments-comment-id-delete",
    "DELETE",
    "/tenant/findings/{finding_id}/comments/{comment_id}",
    "Delete a comment from a tenant finding discussion.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_finding_comments_delete_tenant_findings__finding_id__comments__comment_id__delete",
      role: "operator | admin",
    },
  ),
  "tenant-saved-views-get": stub(
    "tenant-saved-views-get",
    "GET",
    "/tenant/saved-views",
    "List saved dashboard views for the tenant.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_saved_views_list_tenant_saved_views_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-saved-views-view-id-put": stub(
    "tenant-saved-views-view-id-put",
    "PUT",
    "/tenant/saved-views/{view_id}",
    "Save or delete a dashboard view definition.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_saved_views_upsert_tenant_saved_views__view_id__put",
      role: "operator | admin",
    },
  ),
  "tenant-saved-views-view-id-delete": stub(
    "tenant-saved-views-view-id-delete",
    "DELETE",
    "/tenant/saved-views/{view_id}",
    "Save or delete a dashboard view definition.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_saved_views_delete_tenant_saved_views__view_id__delete",
      role: "operator | admin",
    },
  ),
  "tenant-inbox-get": stub(
    "tenant-inbox-get",
    "GET",
    "/tenant/inbox",
    "Read recent tenant alerts and workflow notifications.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_inbox_tenant_inbox_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-war-rooms-get": stub(
    "tenant-war-rooms-get",
    "GET",
    "/tenant/war-rooms",
    "List or create collaboration rooms for incident investigation.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_war_rooms_list_tenant_war_rooms_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-war-rooms-post": stub(
    "tenant-war-rooms-post",
    "POST",
    "/tenant/war-rooms",
    "List or create collaboration rooms for incident investigation.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_war_rooms_create_tenant_war_rooms_post",
      role: "operator | admin",
    },
  ),
  "tenant-ai-query-post": stub(
    "tenant-ai-query-post",
    "POST",
    "/tenant/ai/query",
    "Interpret a natural-language portfolio question and return suggested filters, narrative, and citations.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_ai_query_tenant_ai_query_post",
      role: "viewer | operator | admin",
      notes: ["Review generated content and cited evidence. Draft files and proposed steps are illustrative and must be validated for the target environment before use."],
    },
  ),
  "tenant-ai-executive-narrative-get": stub(
    "tenant-ai-executive-narrative-get",
    "GET",
    "/tenant/ai/executive-narrative",
    "Summarize the latest readiness score and remediation activity for executive review.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_executive_narrative_tenant_ai_executive_narrative_get",
      role: "viewer | operator | admin",
      notes: ["Review generated content and cited evidence. Draft files and proposed steps are illustrative and must be validated for the target environment before use."],
    },
  ),
  "tenant-ai-remediation-pr-draft-post": stub(
    "tenant-ai-remediation-pr-draft-post",
    "POST",
    "/tenant/ai/remediation-pr-draft",
    "Generate illustrative remediation files and a review checklist; this does not open a pull request.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_remediation_pr_draft_tenant_ai_remediation_pr_draft_post",
      role: "operator | admin",
      notes: ["Review generated content and cited evidence. Draft files and proposed steps are illustrative and must be validated for the target environment before use."],
    },
  ),
  "tenant-ai-agentic-plan-remediation-id-get": stub(
    "tenant-ai-agentic-plan-remediation-id-get",
    "GET",
    "/tenant/ai/agentic-plan/{remediation_id}",
    "Return a proposed remediation workflow for human review; requesting a plan executes no steps.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_agentic_plan_tenant_ai_agentic_plan__remediation_id__get",
      role: "viewer | operator | admin",
      notes: ["Review generated content and cited evidence. Draft files and proposed steps are illustrative and must be validated for the target environment before use."],
    },
  ),
  "tenant-incidents-correlated-get": stub(
    "tenant-incidents-correlated-get",
    "GET",
    "/tenant/incidents/correlated",
    "Group recent unresolved tenant alerts into related incidents.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_correlated_incidents_tenant_incidents_correlated_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-cadence-recommendation-get": stub(
    "tenant-cadence-recommendation-get",
    "GET",
    "/tenant/cadence/recommendation",
    "Suggest a scan cadence from tenant activity and existing cadence settings.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_cadence_recommendation_tenant_cadence_recommendation_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-analytics-anomaly-explanations-get": stub(
    "tenant-analytics-anomaly-explanations-get",
    "GET",
    "/tenant/analytics/anomaly-explanations",
    "Explain detected readiness-score changes using the score series.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_anomaly_explanations_tenant_analytics_anomaly_explanations_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-analytics-trajectory-forecast-get": stub(
    "tenant-analytics-trajectory-forecast-get",
    "GET",
    "/tenant/analytics/trajectory-forecast",
    "Explore heuristic readiness projections based on score history and remediation activity.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_trajectory_forecast_tenant_analytics_trajectory_forecast_get",
      role: "viewer | operator | admin",
      notes: ["Planning heuristics and scenario ranges are illustrative, not calibrated confidence intervals or Q-Day predictions. They do not prove that remediation has occurred."],
    },
  ),
  "tenant-evidence-transparency-get": stub(
    "tenant-evidence-transparency-get",
    "GET",
    "/tenant/evidence/transparency",
    "Read transparency-log entries and integrity metadata.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_evidence_transparency_tenant_evidence_transparency_get",
      role: "viewer | operator | admin",
      notes: ["Verification establishes integrity and signing, not complete estate coverage, certification, or formal audit conclusions."],
    },
  ),
  "tenant-evidence-auditor-packet-post": stub(
    "tenant-evidence-auditor-packet-post",
    "POST",
    "/tenant/evidence/auditor-packet",
    "Assemble evidence links for selected tenant-owned scans for independent review.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_auditor_packet_tenant_evidence_auditor_packet_post",
      role: "viewer | operator | admin",
      notes: ["Verification establishes integrity and signing, not complete estate coverage, certification, or formal audit conclusions."],
    },
  ),
  "tenant-portfolio-rollup-get": stub(
    "tenant-portfolio-rollup-get",
    "GET",
    "/tenant/portfolio/rollup",
    "Summarize available child-tenant readiness data.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_portfolio_rollup_tenant_portfolio_rollup_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-benchmarks-percentiles-get": stub(
    "tenant-benchmarks-percentiles-get",
    "GET",
    "/tenant/benchmarks/percentiles",
    "Compare a tenant readiness score with an available benchmark cohort.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_benchmark_percentiles_tenant_benchmarks_percentiles_get",
      role: "viewer | operator | admin",
      notes: ["Inspect cohort availability and sample size. Missing percentile data must not be presented as a measured zero."],
    },
  ),
  "tenant-notification-preferences-get": stub(
    "tenant-notification-preferences-get",
    "GET",
    "/tenant/notification-preferences",
    "Read or save tenant notification preferences.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_notification_preferences_get_tenant_notification_preferences_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-notification-preferences-put": stub(
    "tenant-notification-preferences-put",
    "PUT",
    "/tenant/notification-preferences",
    "Read or save tenant notification preferences.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_notification_preferences_put_tenant_notification_preferences_put",
      role: "operator | admin",
    },
  ),
  "tenant-qros-next-actions-get": stub(
    "tenant-qros-next-actions-get",
    "GET",
    "/tenant/qros/next-actions",
    "List suggested next actions from inventory and workflow heuristics.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_next_actions_tenant_qros_next_actions_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-qros-next-actions-action-id-mutate-post": stub(
    "tenant-qros-next-actions-action-id-mutate-post",
    "POST",
    "/tenant/qros/next-actions/{action_id}/mutate",
    "Assign, snooze, or dismiss a suggested next action.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_nba_mutate_tenant_qros_next_actions__action_id__mutate_post",
      role: "operator | admin",
    },
  ),
  "tenant-qros-morning-briefing-get": stub(
    "tenant-qros-morning-briefing-get",
    "GET",
    "/tenant/qros/morning-briefing",
    "Build a persona-specific briefing from the current dashboard summary.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_morning_briefing_tenant_qros_morning_briefing_get",
      role: "viewer | operator | admin",
    },
  ),
  "tenant-qros-runway-get": stub(
    "tenant-qros-runway-get",
    "GET",
    "/tenant/qros/runway",
    "Explore migration planning horizons and illustrative readiness scenarios.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_runway_tenant_qros_runway_get",
      role: "viewer | operator | admin",
      notes: ["Planning heuristics and scenario ranges are illustrative, not calibrated confidence intervals or Q-Day predictions. They do not prove that remediation has occurred."],
    },
  ),
  "tenant-qros-scenario-simulate-post": stub(
    "tenant-qros-scenario-simulate-post",
    "POST",
    "/tenant/qros/scenario/simulate",
    "Calculate an illustrative readiness scenario without changing inventory or infrastructure.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_scenario_simulate_tenant_qros_scenario_simulate_post",
      role: "viewer | operator | admin",
      notes: ["Planning heuristics and scenario ranges are illustrative, not calibrated confidence intervals or Q-Day predictions. They do not prove that remediation has occurred."],
    },
  ),
  "tenant-qros-digital-twin-scan-id-get": stub(
    "tenant-qros-digital-twin-scan-id-get",
    "GET",
    "/tenant/qros/digital-twin/{scan_id}",
    "Return an inventory graph and optional scenario overlay for a tenant-owned scan.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_digital_twin_tenant_qros_digital_twin__scan_id__get",
      role: "viewer | operator | admin",
      notes: ["Planning heuristics and scenario ranges are illustrative, not calibrated confidence intervals or Q-Day predictions. They do not prove that remediation has occurred."],
    },
  ),
  "tenant-qros-board-deck-post": stub(
    "tenant-qros-board-deck-post",
    "POST",
    "/tenant/qros/board-deck",
    "Generate a board narrative as JSON or PDF for review.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_board_deck_tenant_qros_board_deck_post",
      role: "viewer | operator | admin",
      notes: ["format=pdf returns application/pdf; the default response is JSON."],
    },
  ),
  "tenant-qros-agentic-execute-post": stub(
    "tenant-qros-agentic-execute-post",
    "POST",
    "/tenant/qros/agentic/execute",
    "Preview or execute a supported workflow action with role checks and audit logging.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_agentic_execute_tenant_qros_agentic_execute_post",
      role: "operator | admin",
      notes: ["Start with dryRun=true and review the preview before execution. A failed action may be returned in the response status; HTTP success alone does not prove completion. Draft generation does not open a pull request."],
    },
  ),
  "tenant-qros-marketplace-tiles-get": stub(
    "tenant-qros-marketplace-tiles-get",
    "GET",
    "/tenant/qros/marketplace/tiles",
    "List dashboard tile metadata and saved installation preferences.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_marketplace_tiles_tenant_qros_marketplace_tiles_get",
      role: "viewer | operator | admin",
      notes: ["Installation stores a tile preference; it does not install third-party code or provision a connector."],
    },
  ),
  "tenant-qros-marketplace-tiles-tile-id-install-post": stub(
    "tenant-qros-marketplace-tiles-tile-id-install-post",
    "POST",
    "/tenant/qros/marketplace/tiles/{tile_id}/install",
    "Change the saved installation preference for a dashboard tile.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_marketplace_install_tenant_qros_marketplace_tiles__tile_id__install_post",
      role: "operator | admin",
      notes: ["Installation stores a tile preference; it does not install third-party code or provision a connector."],
    },
  ),
  "tenant-qros-marketplace-tiles-tile-id-install-delete": stub(
    "tenant-qros-marketplace-tiles-tile-id-install-delete",
    "DELETE",
    "/tenant/qros/marketplace/tiles/{tile_id}/install",
    "Change the saved installation preference for a dashboard tile.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_marketplace_uninstall_tenant_qros_marketplace_tiles__tile_id__install_delete",
      role: "operator | admin",
      notes: ["Installation stores a tile preference; it does not install third-party code or provision a connector."],
    },
  ),
  "tenant-qros-push-briefing-send-post": stub(
    "tenant-qros-push-briefing-send-post",
    "POST",
    "/tenant/qros/push-briefing/send",
    "Request immediate briefing delivery through configured notification integrations.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_push_briefing_send_tenant_qros_push_briefing_send_post",
      role: "operator | admin",
      notes: ["Inspect the delivery result for actual outcomes; saving channel preferences alone does not verify delivery."],
    },
  ),
  "tenant-qros-push-briefing-get": stub(
    "tenant-qros-push-briefing-get",
    "GET",
    "/tenant/qros/push-briefing",
    "Read saved briefing delivery preferences and the last scheduled outcome.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_push_briefing_preferences_tenant_qros_push_briefing_get",
      role: "viewer | operator | admin",
      notes: [
        "Returns this tenant's channels, email recipients, cadenceHours, enabled state, firstRunAt, requiresSave, and nullable lastDelivery. Reading does not send or schedule a briefing.",
        "Legacy preferences remain disabled until saved again. Last-delivery counts may be null; outcomeUnknown means acceptance could not be confirmed and must not be interpreted as zero deliveries.",
      ],
    },
  ),
  "tenant-qros-push-briefing-post": stub(
    "tenant-qros-push-briefing-post",
    "POST",
    "/tenant/qros/push-briefing",
    "Save briefing channel and cadence preferences.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_qros_push_briefing_tenant_qros_push_briefing_post",
      role: "operator | admin",
      notes: ["Saves channels, explicit email recipients, cadenceHours (1–168), and enabled state. Scheduled delivery requires persistent storage, a healthy scheduler, and valid destinations. Disabled preferences may omit recipients; identical saves preserve the schedule. Saving does not send immediately."],
    },
  ),
  "public-demo-status-get": stub(
    "public-demo-status-get",
    "GET",
    "/demo/status",
    "Inspect the demonstration service state.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_status_demo_status_get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "public-demo-trend-get": stub(
    "public-demo-trend-get",
    "GET",
    "/demo/trend",
    "Read demonstration readiness history.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_trend_demo_trend_get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-resources-get": stub(
    "tenant-demo-resources-get",
    "GET",
    "/demo/resources",
    "List or create resources in the demonstration inventory.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_list_resources_demo_resources_get",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-resources-post": stub(
    "tenant-demo-resources-post",
    "POST",
    "/demo/resources",
    "List or create resources in the demonstration inventory.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_create_resource_demo_resources_post",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-resources-resource-id-patch": stub(
    "tenant-demo-resources-resource-id-patch",
    "PATCH",
    "/demo/resources/{resource_id}",
    "Update or delete a demonstration inventory resource.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_patch_resource_demo_resources__resource_id__patch",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-resources-resource-id-delete": stub(
    "tenant-demo-resources-resource-id-delete",
    "DELETE",
    "/demo/resources/{resource_id}",
    "Update or delete a demonstration inventory resource.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_delete_resource_demo_resources__resource_id__delete",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-reassess-post": stub(
    "tenant-demo-reassess-post",
    "POST",
    "/demo/reassess",
    "Reassess the demonstration inventory after resource changes.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_reassess_demo_reassess_post",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-scene-scene-id-post": stub(
    "tenant-demo-scene-scene-id-post",
    "POST",
    "/demo/scene/{scene_id}",
    "Apply a predefined demonstration scene.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_apply_scene_demo_scene__scene_id__post",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "public-demo-scenes-get": stub(
    "public-demo-scenes-get",
    "GET",
    "/demo/scenes",
    "List available demonstration scenes.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_scenes_demo_scenes_get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-inject-post": stub(
    "tenant-demo-inject-post",
    "POST",
    "/demo/inject",
    "Inject a simulated event into the demonstration.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_inject_demo_inject_post",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-chaos-post": stub(
    "tenant-demo-chaos-post",
    "POST",
    "/demo/chaos",
    "Configure simulated disruption in the demonstration.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_chaos_demo_chaos_post",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-campaigns-get": stub(
    "tenant-demo-campaigns-get",
    "GET",
    "/demo/campaigns",
    "List saved demonstration campaigns.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_campaigns_demo_campaigns_get",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-campaign-post": stub(
    "tenant-demo-campaign-post",
    "POST",
    "/demo/campaign",
    "Save a demonstration campaign.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_save_campaign_demo_campaign_post",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-campaign-campaign-id-play-post": stub(
    "tenant-demo-campaign-campaign-id-play-post",
    "POST",
    "/demo/campaign/{campaign_id}/play",
    "Start or resume a demonstration campaign.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_play_campaign_demo_campaign__campaign_id__play_post",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-campaign-campaign-id-pause-post": stub(
    "tenant-demo-campaign-campaign-id-pause-post",
    "POST",
    "/demo/campaign/{campaign_id}/pause",
    "Pause a demonstration campaign.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_pause_campaign_demo_campaign__campaign_id__pause_post",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "public-demo-campaign-campaign-id-state-get": stub(
    "public-demo-campaign-campaign-id-state-get",
    "GET",
    "/demo/campaign/{campaign_id}/state",
    "Inspect a demonstration campaign state.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_campaign_state_demo_campaign__campaign_id__state_get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "tenant-demo-campaign-campaign-id-scrub-post": stub(
    "tenant-demo-campaign-campaign-id-scrub-post",
    "POST",
    "/demo/campaign/{campaign_id}/scrub",
    "Move a demonstration campaign to a selected time.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_scrub_campaign_demo_campaign__campaign_id__scrub_post",
      role: "API key",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "public-demo-compliance-get": stub(
    "public-demo-compliance-get",
    "GET",
    "/demo/compliance",
    "View framework mappings for demonstration inventory; this is not compliance attestation.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_compliance_demo_compliance_get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "public-demo-portfolio-get": stub(
    "public-demo-portfolio-get",
    "GET",
    "/demo/portfolio",
    "Read demonstration portfolio snapshots.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_portfolio_demo_portfolio_get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "public-demo-graph-get": stub(
    "public-demo-graph-get",
    "GET",
    "/demo/graph",
    "Inspect a demonstration inventory dependency graph.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_graph_demo_graph_get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "public-demo-narration-get": stub(
    "public-demo-narration-get",
    "GET",
    "/demo/narration",
    "Read the current demonstration narrative.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_narration_demo_narration_get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
    },
  ),
  "public-demo-verify-snapshot-id-get": stub(
    "public-demo-verify-snapshot-id-get",
    "GET",
    "/demo/verify/{snapshot_id}",
    "Verify a demonstration snapshot signature and integrity.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_verify_demo_verify__snapshot_id__get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage.", "Verification establishes integrity and signing, not complete estate coverage, certification, or formal audit conclusions."],
    },
  ),
  "public-demo-events-get": stub(
    "public-demo-events-get",
    "GET",
    "/demo/events",
    "Subscribe to server-sent demonstration events.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/demo/demo_events_demo_events_get",
      role: "none",
      notes: ["Requires demo mode (QTANGL_DEMO_ENABLED). Demonstration data is separate from customer inventory and does not prove estate coverage."],
      contentType: "text/event-stream",
    },
  ),
  "tenant-integrations-slack-actions-post": stub(
    "tenant-integrations-slack-actions-post",
    "POST",
    "/integrations/slack/actions",
    "Receive JSON alert acknowledgement or assignment actions for a Slack integration.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/integrations/slack_inbound_action_integrations_slack_actions_post",
      role: "operator | admin",
      notes: ["Requires an authenticated custom JSON relay using tenant API/session credentials with operator or admin access. Native provider signature validation is not supported. Any tenantId or X-Qtangl-Tenant hint must match the authenticated tenant. Assignment actions currently create an audit entry."],
    },
  ),
  "tenant-integrations-teams-actions-post": stub(
    "tenant-integrations-teams-actions-post",
    "POST",
    "/integrations/teams/actions",
    "Receive JSON alert acknowledgement or assignment actions for a Teams integration.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/integrations/teams_inbound_action_integrations_teams_actions_post",
      role: "operator | admin",
      notes: ["Requires an authenticated custom JSON relay using tenant API/session credentials with operator or admin access. Native provider signature validation is not supported. Any tenantId or X-Qtangl-Tenant hint must match the authenticated tenant. Assignment actions currently create an audit entry."],
    },
  ),
  "public-verify-branding-get": stub(
    "public-verify-branding-get",
    "GET",
    "/public/verify/branding",
    "Resolve public verification-page branding for a known scan.",
    false,
    {
      schemaUrl: "https://api.qtangl.com/docs#/public/public_verify_branding_public_verify_branding_get",
      role: "none",
      notes: ["Verification establishes integrity and signing, not complete estate coverage, certification, or formal audit conclusions."],
    },
  ),
  "tenant-partner-program-get": stub(
    "tenant-partner-program-get",
    "GET",
    "/tenant/partner/program",
    "Inspect partner program limits and current child-tenant usage.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_partner_program_tenant_partner_program_get",
      role: "viewer | operator | admin",
      notes: ["Requires partner API access for the authenticated tenant."],
    },
  ),
  "tenant-partner-portfolio-board-get": stub(
    "tenant-partner-portfolio-board-get",
    "GET",
    "/tenant/partner/portfolio-board",
    "Export linked-customer portfolio summaries as PDF or CSV.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_partner_portfolio_board_tenant_partner_portfolio_board_get",
      role: "viewer | operator | admin",
      notes: ["Requires partner API access for the authenticated tenant.", "Requires the enterprise or convert tier; child access and provisioning limits also apply where relevant.", "format=csv returns text/csv; otherwise the response is application/pdf."],
      contentType: "application/pdf",
    },
  ),
  "tenant-partner-bulk-weekly-digest-post": stub(
    "tenant-partner-bulk-weekly-digest-post",
    "POST",
    "/tenant/partner/bulk/weekly-digest",
    "Set the weekly-digest preference across linked customer workspaces.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_partner_bulk_weekly_digest_tenant_partner_bulk_weekly_digest_post",
      role: "admin",
      notes: ["Requires partner API access for the authenticated tenant.", "Requires the enterprise or convert tier; child access and provisioning limits also apply where relevant."],
    },
  ),
  "tenant-partner-bulk-schedule-template-post": stub(
    "tenant-partner-bulk-schedule-template-post",
    "POST",
    "/tenant/partner/bulk/schedule-template",
    "Create initial scan schedules for eligible linked customer workspaces.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_partner_bulk_schedule_template_tenant_partner_bulk_schedule_template_post",
      role: "admin",
      notes: ["Requires partner API access for the authenticated tenant.", "Requires the enterprise or convert tier; child access and provisioning limits also apply where relevant."],
    },
  ),
  "tenant-partner-deal-registration-post": stub(
    "tenant-partner-deal-registration-post",
    "POST",
    "/tenant/partner/deal-registration",
    "Record a partner deal registration and notify configured operations recipients.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_partner_deal_registration_tenant_partner_deal_registration_post",
      role: "operator | admin",
      notes: ["Requires partner API access for the authenticated tenant."],
    },
  ),
  "tenant-partner-usage-export-get": stub(
    "tenant-partner-usage-export-get",
    "GET",
    "/tenant/partner/usage-export",
    "Export linked-customer portfolio summaries as CSV.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_partner_usage_export_tenant_partner_usage_export_get",
      role: "viewer | operator | admin",
      notes: ["Requires partner API access for the authenticated tenant.", "Requires the enterprise or convert tier; child access and provisioning limits also apply where relevant."],
      contentType: "text/csv",
    },
  ),
  "tenant-partner-children-child-tenant-id-delete": stub(
    "tenant-partner-children-child-tenant-id-delete",
    "DELETE",
    "/tenant/partner/children/{child_tenant_id}",
    "Update a linked customer label or unlink a customer workspace.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_partner_unlink_child_tenant_partner_children__child_tenant_id__delete",
      role: "admin",
      notes: ["Requires the enterprise or convert tier; child access and provisioning limits also apply where relevant."],
    },
  ),
  "tenant-partner-children-child-tenant-id-patch": stub(
    "tenant-partner-children-child-tenant-id-patch",
    "PATCH",
    "/tenant/partner/children/{child_tenant_id}",
    "Update a linked customer label or unlink a customer workspace.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_partner_update_child_label_tenant_partner_children__child_tenant_id__patch",
      role: "admin",
      notes: ["Requires the enterprise or convert tier; child access and provisioning limits also apply where relevant."],
    },
  ),
  "tenant-partner-provision-child-post": stub(
    "tenant-partner-provision-child-post",
    "POST",
    "/tenant/partner/provision-child",
    "Provision a linked customer workspace within partner tier limits.",
    true,
    {
      schemaUrl: "https://api.qtangl.com/docs#/tenant/tenant_partner_provision_child_tenant_partner_provision_child_post",
      role: "admin",
      notes: ["Requires the enterprise or convert tier; child access and provisioning limits also apply where relevant."],
    },
  ),
};
