import type { DocsEndpoint } from "@/lib/docs/types";
import { defineEndpoint, ROLE_ADMIN, ROLE_ANY, ROLE_WRITE } from "@/lib/docs/endpoint-factory";

const scanIdParam = {
  name: "scan_id",
  type: "string",
  required: true,
  description: "Scan identifier.",
};

const remediationIdField = {
  name: "remediationId",
  type: "string",
  required: true,
  description: "Remediation backlog item id.",
};

export const tenantEndpoints: Record<string, DocsEndpoint> = {
  "tenant-me": defineEndpoint("tenant-me", {
    method: "GET",
    path: "/tenant/me",
    status: "ga",
    summary: "Return tenant identity, active role, and enabled feature entitlements.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "status", type: '"success"', required: true, description: "Request completed." },
      { name: "tenantId", type: "string", required: true, description: "Current tenant id." },
      { name: "role", type: "string", required: true, description: "Role resolved from auth token." },
      { name: "entitlements", type: "object", required: true, description: "Subscription feature flags." },
    ],
    examples: [{ label: "Tenant context", response: { status: "success", tenantId: "tenant_demo", role: "admin" } }],
  }),
  "tenant-scans": defineEndpoint("tenant-scans", {
    method: "GET",
    path: "/tenant/scans",
    status: "ga",
    summary: "List recent tenant scans with lifecycle status and report availability.",
    auth: true,
    role: ROLE_ANY,
    queryParams: [
      { name: "limit", type: "integer", required: false, default: "25", description: "Result size (1-100)." },
    ],
    responseFields: [
      { name: "count", type: "integer", required: true, description: "Number of scan rows returned." },
      { name: "scans", type: "object[]", required: true, description: "Scan summaries and metadata." },
    ],
    examples: [{ label: "Recent scans", response: { status: "success", count: 2, scans: [{ scanId: "scan_001", status: "done" }] } }],
  }),
  "tenant-scan-detail": defineEndpoint("tenant-scan-detail", {
    method: "GET",
    path: "/tenant/scans/{scan_id}",
    summary: "Get full scan payload including timeline, report fields, and remediation completion.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "scanId", type: "string", required: true, description: "Requested scan id." },
      { name: "jobStatus", type: "string", required: true, description: "Current job state." },
      { name: "timeline", type: "object[]", required: true, description: "Step-by-step execution events." },
      { name: "remediationStatus", type: "object[]", required: false, description: "Per-item remediation state." },
    ],
    examples: [{ label: "Detailed scan", response: { status: "success", scanId: "scan_001", jobStatus: "done", timeline: [] } }],
  }),
  "tenant-scan-delete": defineEndpoint("tenant-scan-delete", {
    method: "DELETE",
    path: "/tenant/scans/{scan_id}",
    summary: "Delete a tenant-owned scan and remove associated report artifacts.",
    auth: true,
    role: ROLE_WRITE,
    responseFields: [
      { name: "scanId", type: "string", required: true, description: "Deleted scan id." },
      { name: "deleted", type: "boolean", required: true, description: "Always true when successful." },
    ],
    examples: [{ label: "Delete scan", response: { status: "success", scanId: "scan_001", deleted: true } }],
  }),
  "tenant-scan-report": defineEndpoint("tenant-scan-report", {
    method: "GET",
    path: "/tenant/scans/{scan_id}/report",
    summary: "Return scan report in JSON variants or downloadable PDF/ZIP bundles.",
    auth: true,
    role: ROLE_ANY,
    queryParams: [
      {
        name: "format",
        type: '"pdf" | "json" | "bundle" | "executive" | "board" | "auditor"',
        required: false,
        default: "pdf",
        description: "Response report format.",
      },
    ],
    formatMatrix: [
      { name: "pdf", type: "application/pdf", description: "Full migration report PDF." },
      { name: "json", type: "application/json", description: "Structured report payload." },
      { name: "bundle", type: "application/zip", description: "Evidence bundle ZIP export." },
      { name: "executive", type: "application/json", description: "Executive summary JSON." },
      { name: "board", type: "application/json", description: "Board-view JSON payload." },
      { name: "auditor", type: "application/json", description: "Auditor-oriented JSON payload." },
    ],
    responseFields: [
      { name: "content", type: "binary | object", required: true, description: "Report body based on selected format." },
    ],
    examples: [{ label: "Report JSON", response: { status: "success", report: { readinessScore: 83 } } }],
    notes: ["Use format=bundle for ZIP evidence download."],
  }),
  "tenant-scan-email": defineEndpoint("tenant-scan-email", {
    method: "POST",
    path: "/tenant/scans/{scan_id}/email",
    summary: "Email a scan report link to a recipient mailbox.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [{ name: "email", type: "string", required: true, description: "Destination email address." }],
    responseFields: [
      { name: "sent", type: "boolean", required: true, description: "Whether message dispatch succeeded." },
      { name: "provider", type: "string", required: false, description: "Email provider implementation." },
    ],
    examples: [{ label: "Send report email", request: { email: "security@example.com" }, response: { status: "success", sent: true } }],
  }),
  "tenant-export": defineEndpoint("tenant-export", {
    method: "GET",
    path: "/tenant/export",
    summary: "Export scan metadata, remediation states, and velocity metrics for the tenant.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "exportedAt", type: "string (ISO8601)", required: true, description: "Export generation time." },
      { name: "scans", type: "object[]", required: true, description: "Exported scan metadata." },
      { name: "remediationByScan", type: "object", required: true, description: "Remediation rows grouped by scan." },
    ],
    examples: [{ label: "Tenant export", response: { status: "success", exportedAt: "2026-06-09T18:00:00Z", scans: [] } }],
  }),
  "tenant-slo": defineEndpoint("tenant-slo", {
    method: "GET",
    path: "/tenant/slo",
    summary: "Compute tenant reliability and report-availability service level metrics.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "metrics", type: "object", required: true, description: "SLO metrics including success and report rates." },
    ],
    examples: [{ label: "SLO metrics", response: { status: "success", metrics: { scanSuccessRatePct: 100, targetSloPct: 99 } } }],
  }),
  "tenant-remediation-list": defineEndpoint("tenant-remediation-list", {
    method: "GET",
    path: "/tenant/scans/{scan_id}/remediation",
    summary: "List remediation statuses tracked for a scan backlog.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "scanId", type: "string", required: true, description: "Scan id." },
      { name: "items", type: "object[]", required: true, description: "Tracked remediation status rows." },
    ],
    examples: [{ label: "Remediation list", response: { status: "success", scanId: "scan_001", items: [] } }],
  }),
  "tenant-remediation-update": defineEndpoint("tenant-remediation-update", {
    method: "POST",
    path: "/tenant/scans/{scan_id}/remediation",
    summary: "Create or update remediation ownership, status, notes, and target date.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      remediationIdField,
      { name: "status", type: "string", required: true, description: "New remediation state." },
      { name: "owner", type: "string", required: false, description: "Assigned owner." },
      { name: "notes", type: "string", required: false, description: "Operator notes." },
      { name: "targetDate", type: "string (ISO8601)", required: false, description: "Desired completion date." },
      { name: "assetId", type: "string", required: false, description: "Related asset identifier." },
    ],
    responseFields: [{ name: "item", type: "object", required: true, description: "Saved remediation row." }],
    examples: [
      {
        label: "Update remediation",
        request: { remediationId: "rem_001", status: "in_progress", owner: "alice@example.com" },
        response: { status: "success", item: { remediationId: "rem_001", status: "in_progress" } },
      },
    ],
  }),
  "tenant-remediation-automate": defineEndpoint("tenant-remediation-automate", {
    method: "POST",
    path: "/tenant/scans/{scan_id}/remediation/automate",
    summary: "Trigger automated remediation actions like ACME reissue, GitHub PR, or Venafi checks.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      remediationIdField,
      { name: "action", type: '"acme" | "github_pr" | "venafi"', required: true, description: "Automation action type." },
      { name: "domain", type: "string", required: false, description: "Domain override for ACME." },
      { name: "repo", type: "string", required: false, description: "Repository for GitHub PR action." },
      { name: "branch", type: "string", required: false, description: "Target branch name." },
      { name: "title", type: "string", required: false, description: "PR title override." },
      { name: "policyId", type: "string", required: false, description: "Policy id for Venafi checks." },
    ],
    responseFields: [{ name: "result", type: "object", required: true, description: "Automation execution output." }],
    examples: [
      {
        label: "Open remediation PR",
        request: { remediationId: "rem_001", action: "github_pr", repo: "qtangl/infra" },
        response: { status: "success", scanId: "scan_001", result: { status: "ok" } },
      },
    ],
  }),
  "tenant-remediation-verify": defineEndpoint("tenant-remediation-verify", {
    method: "POST",
    path: "/tenant/scans/{scan_id}/remediation/verify",
    summary: "Verify that a remediation item is fixed by comparing baseline and verification scans.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      remediationIdField,
      { name: "verifyScanId", type: "string", required: true, description: "Follow-up scan id used for verification." },
    ],
    responseFields: [
      { name: "verified", type: "boolean", required: true, description: "Whether fix verification passed." },
      { name: "reason", type: "string", required: false, description: "Verification explanation." },
    ],
    examples: [
      {
        label: "Verification passed",
        request: { remediationId: "rem_001", verifyScanId: "scan_002" },
        response: { status: "success", verified: true },
      },
    ],
  }),
  "tenant-remediation-intelligence": defineEndpoint("tenant-remediation-intelligence", {
    method: "GET",
    path: "/tenant/scans/{scan_id}/remediation/intelligence",
    summary: "Generate AI-backed remediation plans and sequencing recommendations.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "plans", type: "object[]", required: true, description: "Recommended remediation plans." }],
    examples: [{ label: "Remediation plans", response: { status: "success", scanId: "scan_001", plans: [] } }],
  }),
  "tenant-remediation-simulate": defineEndpoint("tenant-remediation-simulate", {
    method: "POST",
    path: "/tenant/scans/{scan_id}/remediation/simulate",
    summary: "Simulate post-remediation readiness projection for selected remediation ids.",
    auth: true,
    role: ROLE_ANY,
    requestFields: [
      { name: "remediationIds", type: "string[]", required: false, description: "Subset to model in simulation." },
    ],
    responseFields: [{ name: "projection", type: "object", required: true, description: "Projected readiness deltas." }],
    examples: [
      {
        label: "Simulate readiness",
        request: { remediationIds: ["rem_001", "rem_005"] },
        response: { status: "success", projection: { readinessScore: 91 } },
      },
    ],
  }),
  "tenant-schedules-list": defineEndpoint("tenant-schedules-list", {
    method: "GET",
    path: "/tenant/schedules",
    summary: "List tenant monitoring schedules and cadence configuration.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "schedules", type: "object[]", required: true, description: "Schedule definitions for tenant jobs." }],
    examples: [{ label: "List schedules", response: { status: "success", schedules: [] } }],
  }),
  "tenant-schedules-create": defineEndpoint("tenant-schedules-create", {
    method: "POST",
    path: "/tenant/schedules",
    summary: "Create recurring scan or cloud-pull schedule with notifications.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "scenarioId", type: "string", required: false, default: "bank-tls-inventory", description: "Scenario id to execute." },
      { name: "target", type: "string", required: false, description: "Target domain or dataset." },
      { name: "cadenceHours", type: "integer", required: false, default: "168", description: "Run interval in hours." },
      { name: "notifyEmail", type: "string", required: false, description: "Notification destination." },
      { name: "cloudImportPayload", type: "string", required: false, description: "Serialized import payload." },
      { name: "jobType", type: '"scan" | "cloud_pull"', required: false, default: "scan", description: "Scheduled workflow type." },
      { name: "integrationProvider", type: "string", required: false, description: "Cloud provider for cloud_pull jobType." },
    ],
    responseFields: [{ name: "schedule", type: "object", required: true, description: "Persisted schedule row." }],
    examples: [
      {
        label: "Create weekly scan",
        request: { scenarioId: "bank-tls-inventory", cadenceHours: 168 },
        response: { status: "success", schedule: { id: "sched_001", cadenceHours: 168 } },
      },
    ],
  }),
  "tenant-schedules-patch": defineEndpoint("tenant-schedules-patch", {
    method: "PATCH",
    path: "/tenant/schedules/{schedule_id}",
    summary: "Partially update schedule cadence, notification email, or active state.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "cadenceHours", type: "integer", required: false, description: "Updated cadence in hours." },
      { name: "notifyEmail", type: "string", required: false, description: "Updated notification email." },
      { name: "active", type: "boolean", required: false, description: "Enable or disable schedule." },
    ],
    responseFields: [{ name: "schedule", type: "object", required: true, description: "Updated schedule definition." }],
    examples: [
      {
        label: "Pause schedule",
        request: { active: false },
        response: { status: "success", schedule: { id: "sched_001", active: false } },
      },
    ],
  }),
  "tenant-schedules-runs": defineEndpoint("tenant-schedules-runs", {
    method: "GET",
    path: "/tenant/schedules/{schedule_id}/runs",
    summary: "Retrieve run history for a schedule id.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "runs", type: "object[]", required: true, description: "Historical schedule run records." }],
    examples: [{ label: "Schedule history", response: { status: "success", scheduleId: "sched_001", runs: [] } }],
  }),
  "tenant-schedules-delete": defineEndpoint("tenant-schedules-delete", {
    method: "DELETE",
    path: "/tenant/schedules/{schedule_id}",
    summary: "Delete a schedule and stop future recurring runs.",
    auth: true,
    role: ROLE_WRITE,
    responseFields: [
      { name: "scheduleId", type: "string", required: true, description: "Deleted schedule id." },
      { name: "deleted", type: "boolean", required: true, description: "Deletion status." },
    ],
    examples: [{ label: "Delete schedule", response: { status: "success", scheduleId: "sched_001", deleted: true } }],
  }),
  "tenant-settings-get": defineEndpoint("tenant-settings-get", {
    method: "GET",
    path: "/tenant/settings",
    summary: "Load tenant-level monitoring, retention, and benchmark settings.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "settings", type: "object", required: true, description: "Current tenant settings record." }],
    examples: [{ label: "Settings payload", response: { status: "success", settings: { benchmarkOptIn: false } } }],
  }),
  "tenant-settings-put": defineEndpoint("tenant-settings-put", {
    method: "PUT",
    path: "/tenant/settings",
    summary: "Update tenant settings such as retention policy, thresholds, and webhook secret.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "readinessDropThreshold", type: "number", required: false, description: "Alert threshold for readiness drop." },
      { name: "alertOnNewQuantumVulnerable", type: "boolean", required: false, description: "Enable vulnerable-asset alerting." },
      { name: "certExpiryDays", type: "integer", required: false, description: "Certificate expiry warning window." },
      { name: "webhookSigningSecret", type: "string", required: false, description: "Secret used for webhook signing." },
      { name: "autoRetainScans", type: "boolean", required: false, description: "Automatically retain completed scans." },
      { name: "evidenceRetentionMonths", type: "integer", required: false, description: "Evidence retention duration (1-120)." },
      { name: "benchmarkOptIn", type: "boolean", required: false, description: "Enable benchmark and drift analytics." },
      { name: "industry", type: "string", required: false, description: "Industry cohort used for benchmarking." },
    ],
    responseFields: [{ name: "settings", type: "object", required: true, description: "Persisted settings record." }],
    examples: [
      {
        label: "Enable benchmarking",
        request: { benchmarkOptIn: true, industry: "financial" },
        response: { status: "success", settings: { benchmarkOptIn: true, industry: "financial" } },
      },
    ],
  }),
  "tenant-audit": defineEndpoint("tenant-audit", {
    method: "GET",
    path: "/tenant/audit",
    summary: "List tenant audit entries with optional action/since filters and cursor pagination.",
    auth: true,
    role: ROLE_ADMIN,
    queryParams: [
      { name: "limit", type: "integer", required: false, default: "50", description: "Entries per page (1-500)." },
      { name: "action", type: "string", required: false, description: "Action prefix filter." },
      { name: "since", type: "string (ISO8601)", required: false, description: "Only return entries after timestamp." },
      { name: "cursor", type: "string", required: false, description: "Cursor for next page retrieval." },
    ],
    responseFields: [
      { name: "entries", type: "object[]", required: true, description: "Audit events." },
      { name: "nextCursor", type: "string | null", required: false, description: "Cursor for subsequent page." },
    ],
    examples: [{ label: "Audit page", response: { status: "success", entries: [], nextCursor: null } }],
  }),
  "tenant-audit-export": defineEndpoint("tenant-audit-export", {
    method: "GET",
    path: "/tenant/audit/export",
    summary: "Export audit log as NDJSON for archival or external compliance tooling.",
    auth: true,
    role: ROLE_ADMIN,
    contentType: "application/x-ndjson",
    queryParams: [
      { name: "limit", type: "integer", required: false, default: "500", description: "Entry limit (1-5000)." },
      { name: "since", type: "string (ISO8601)", required: false, description: "Export events after timestamp." },
    ],
    responseFields: [{ name: "ndjson", type: "string", required: true, description: "Line-delimited JSON audit events." }],
    examples: [{ label: "NDJSON export", response: '{"action":"scan.delete","tenant_id":"tenant_demo"}\n' }],
  }),
  "tenant-share-create": defineEndpoint("tenant-share-create", {
    method: "POST",
    path: "/tenant/scans/{scan_id}/share",
    summary: "Create expiring share links for report, bundle, or passport access.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "expiresHours", type: "integer", required: false, default: "168", description: "Link TTL in hours (1-720)." },
      { name: "label", type: "string", required: false, description: "Human-readable link label." },
      { name: "scope", type: '"report" | "bundle" | "passport"', required: false, default: "report", description: "Shared artifact scope." },
    ],
    responseFields: [
      { name: "url", type: "string", required: true, description: "Public share URL." },
      { name: "token", type: "string", required: true, description: "Opaque share token." },
      { name: "expiresAt", type: "string (ISO8601)", required: true, description: "Expiration timestamp." },
      { name: "scope", type: "string", required: true, description: "Effective link scope." },
    ],
    examples: [
      {
        label: "Create report link",
        request: { label: "Board packet", scope: "report", expiresHours: 168 },
        response: { status: "success", url: "https://www.qtangl.com/r/abc123", scope: "report" },
      },
    ],
  }),
  "tenant-passport": defineEndpoint("tenant-passport", {
    method: "POST",
    path: "/tenant/scans/{scan_id}/share",
    summary: "Backward-compatible alias for creating tenant passport share links.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "expiresHours", type: "integer", required: false, default: "168", description: "Link TTL in hours (1-720)." },
      { name: "label", type: "string", required: false, description: "Human-readable link label." },
      { name: "scope", type: '"report" | "bundle" | "passport"', required: false, default: "passport", description: "Set passport for full handoff scope." },
    ],
    responseFields: [
      { name: "url", type: "string", required: true, description: "Public share URL." },
      { name: "token", type: "string", required: true, description: "Opaque share token." },
    ],
    examples: [
      {
        label: "Create passport link",
        request: { label: "Auditor handoff", scope: "passport" },
        response: { status: "success", url: "https://www.qtangl.com/r/passport01", scope: "passport" },
      },
    ],
    notes: [
      "Alias of tenant-share-create. Canonical docs: /docs/reference/tenant/share-create.",
      "Legacy bookmark URL: /docs/reference/pqc/passport.",
    ],
  }),
  "tenant-passports": defineEndpoint("tenant-passports", {
    method: "GET",
    path: "/tenant/passports",
    summary: "List active tenant share/passport links, optionally filtered by scan id.",
    auth: true,
    role: ROLE_ANY,
    queryParams: [
      { name: "scanId", type: "string", required: false, description: "Optional scan filter." },
    ],
    responseFields: [{ name: "links", type: "object[]", required: true, description: "Active share links." }],
    examples: [{ label: "Passport links", response: { status: "success", links: [] } }],
  }),
  "tenant-share-revoke": defineEndpoint("tenant-share-revoke", {
    method: "DELETE",
    path: "/tenant/share/{link_id}",
    summary: "Revoke a previously issued share or passport link.",
    auth: true,
    role: ROLE_WRITE,
    responseFields: [
      { name: "linkId", type: "string", required: true, description: "Revoked link id." },
      { name: "revoked", type: "boolean", required: true, description: "Revocation result." },
    ],
    examples: [{ label: "Revoke link", response: { status: "success", linkId: "link_001", revoked: true } }],
  }),
  "tenant-portfolio-list": defineEndpoint("tenant-portfolio-list", {
    method: "GET",
    path: "/tenant/portfolio",
    summary: "List tracked portfolio targets and readiness rollup.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "targets", type: "object[]", required: true, description: "Tracked portfolio targets." },
      { name: "rollup", type: "object", required: true, description: "Cross-target readiness summary." },
    ],
    examples: [{ label: "Portfolio view", response: { status: "success", targets: [], rollup: {} } }],
  }),
  "tenant-portfolio-add": defineEndpoint("tenant-portfolio-add", {
    method: "POST",
    path: "/tenant/portfolio",
    summary: "Add a portfolio target and optionally create an auto-monitoring schedule.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "target", type: "string", required: true, description: "Domain or asset target." },
      { name: "businessUnit", type: "string", required: false, default: "default", description: "Owning business unit label." },
      { name: "label", type: "string", required: false, description: "Friendly display label." },
      { name: "autoSchedule", type: "boolean", required: false, default: "false", description: "Create recurring schedule if enabled." },
      { name: "cadenceHours", type: "integer", required: false, default: "168", description: "Schedule cadence in hours when autoSchedule is true." },
      { name: "notifyEmail", type: "string", required: false, description: "Optional notification email for auto schedule." },
    ],
    responseFields: [
      { name: "target", type: "object", required: true, description: "Newly created portfolio target." },
      { name: "schedule", type: "object | null", required: false, description: "Auto-created schedule (if any)." },
    ],
    examples: [
      {
        label: "Add portfolio target",
        request: { target: "api.example.com", businessUnit: "payments", autoSchedule: true },
        response: { status: "success", target: { id: "pt_001", target: "api.example.com" } },
      },
    ],
  }),
  "tenant-portfolio-command-center": defineEndpoint("tenant-portfolio-command-center", {
    method: "GET",
    path: "/tenant/portfolio/command-center",
    summary: "Return command-center aggregates and weekly executive digest for portfolio monitoring.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "commandCenter", type: "object", required: true, description: "Portfolio health command-center payload." },
      { name: "weeklyDigest", type: "object", required: true, description: "Weekly executive summary." },
    ],
    examples: [{ label: "Command center", response: { status: "success", commandCenter: {}, weeklyDigest: {} } }],
  }),
  "tenant-partner-children-list": defineEndpoint("tenant-partner-children-list", {
    method: "GET",
    path: "/tenant/partner/children",
    summary: "List child tenants linked to a partner parent tenant.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "children", type: "object[]", required: true, description: "Linked child tenant records." }],
    examples: [{ label: "Child tenants", response: { status: "success", children: [] } }],
  }),
  "tenant-partner-children-link": defineEndpoint("tenant-partner-children-link", {
    method: "POST",
    path: "/tenant/partner/children",
    summary: "Link a child tenant to the current partner tenant.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "childTenantId", type: "string", required: true, description: "Tenant id of child account." },
      { name: "label", type: "string", required: false, description: "Optional display label." },
    ],
    responseFields: [{ name: "child", type: "object", required: true, description: "Linked child tenant details." }],
    examples: [
      {
        label: "Link child tenant",
        request: { childTenantId: "tenant_child_01", label: "Regional BU" },
        response: { status: "success", child: { childTenantId: "tenant_child_01" } },
      },
    ],
  }),
  "tenant-webhooks-list": defineEndpoint("tenant-webhooks-list", {
    method: "GET",
    path: "/tenant/webhooks",
    summary: "List configured webhook subscriptions for tenant events.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "webhooks", type: "object[]", required: true, description: "Webhook destination configurations." }],
    examples: [{ label: "Webhook list", response: { status: "success", webhooks: [] } }],
  }),
  "tenant-webhooks-create": defineEndpoint("tenant-webhooks-create", {
    method: "POST",
    path: "/tenant/webhooks",
    summary: "Create a tenant webhook subscription endpoint.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "url", type: "string", required: true, description: "Webhook target URL." },
      { name: "events", type: "string", required: false, default: "scan.complete", description: "Comma-separated events." },
    ],
    responseFields: [{ name: "webhook", type: "object", required: true, description: "Created webhook record." }],
    examples: [
      {
        label: "Create webhook",
        request: { url: "https://hooks.example.com/qtangl", events: "scan.complete,scan.failed" },
        response: { status: "success", webhook: { id: "wh_001" } },
      },
    ],
  }),
  "tenant-webhooks-delete": defineEndpoint("tenant-webhooks-delete", {
    method: "DELETE",
    path: "/tenant/webhooks/{webhook_id}",
    summary: "Delete a configured webhook subscription.",
    auth: true,
    role: ROLE_WRITE,
    responseFields: [
      { name: "webhookId", type: "string", required: true, description: "Deleted webhook id." },
      { name: "deleted", type: "boolean", required: true, description: "Deletion result." },
    ],
    examples: [{ label: "Delete webhook", response: { status: "success", webhookId: "wh_001", deleted: true } }],
  }),
  "tenant-webhooks-dlq": defineEndpoint("tenant-webhooks-dlq", {
    method: "GET",
    path: "/tenant/webhooks/dlq",
    summary: "List webhook dead-letter queue entries for failed deliveries.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "items", type: "object[]", required: true, description: "Dead-letter webhook delivery records." }],
    examples: [{ label: "DLQ items", response: { status: "success", items: [] } }],
  }),
  "tenant-webhooks-replay": defineEndpoint("tenant-webhooks-replay", {
    method: "POST",
    path: "/tenant/webhooks/replay",
    summary: "Replay a dead-letter webhook event using tenant signing secret.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [{ name: "deadLetterId", type: "string", required: true, description: "Dead-letter event id." }],
    responseFields: [{ name: "replayed", type: "boolean", required: true, description: "Replay operation result." }],
    examples: [{ label: "Replay dead-letter", request: { deadLetterId: "dlq_001" }, response: { status: "success", replayed: true } }],
  }),
  "tenant-integrations-list": defineEndpoint("tenant-integrations-list", {
    method: "GET",
    path: "/tenant/integrations",
    summary: "List generic integration configurations for the tenant.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "integrations", type: "object[]", required: true, description: "Configured integration entries." }],
    examples: [{ label: "Integrations", response: { status: "success", integrations: [] } }],
  }),
  "tenant-integrations-upsert": defineEndpoint("tenant-integrations-upsert", {
    method: "POST",
    path: "/tenant/integrations/{provider}",
    summary: "Create or update provider integration configuration.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [{ name: "config", type: "object", required: true, description: "Provider-specific integration config payload." }],
    responseFields: [{ name: "integration", type: "object", required: true, description: "Saved integration config." }],
    examples: [
      {
        label: "Upsert Jira integration",
        request: { config: { baseUrl: "https://jira.example.com", projectKey: "SEC" } },
        response: { status: "success", integration: { provider: "jira" } },
      },
    ],
  }),
  "tenant-integrations-push": defineEndpoint("tenant-integrations-push", {
    method: "POST",
    path: "/tenant/scans/{scan_id}/integrations/push",
    summary: "Push a remediation item to an external ticketing integration.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      remediationIdField,
      { name: "provider", type: "string", required: false, default: "jira", description: "Ticketing provider." },
    ],
    responseFields: [
      { name: "ticketId", type: "string", required: false, description: "Created external ticket id." },
      { name: "provider", type: "string", required: false, description: "Provider used for push." },
    ],
    examples: [
      {
        label: "Push remediation ticket",
        request: { remediationId: "rem_001", provider: "jira" },
        response: { status: "success", provider: "jira", ticketId: "SEC-324" },
      },
    ],
  }),
  "tenant-integrations-pull": defineEndpoint("tenant-integrations-pull", {
    method: "POST",
    path: "/tenant/integrations/pull",
    summary: "Pull latest ticket status for a remediation item from connected integrations.",
    auth: true,
    role: ROLE_ANY,
    requestFields: [remediationIdField],
    responseFields: [{ name: "ticket", type: "object", required: false, description: "Current external ticket status." }],
    examples: [{ label: "Pull ticket status", request: { remediationId: "rem_001" }, response: { status: "success", ticket: { state: "Done" } } }],
  }),
  "tenant-cloud-import": defineEndpoint("tenant-cloud-import", {
    method: "POST",
    path: "/tenant/cloud-import",
    summary: "Parse cloud inventory payload (JSON/CSV) into normalized rows for upload workflows.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "payload", type: "string", required: true, description: "Raw cloud-export data content." },
      { name: "filename", type: "string", required: false, default: "import.json", description: "Original filename hint for parser." },
    ],
    responseFields: [
      { name: "count", type: "integer", required: true, description: "Number of parsed rows." },
      { name: "rows", type: "object[]", required: true, description: "Normalized inventory rows." },
    ],
    examples: [
      {
        label: "Parse cloud export",
        request: { filename: "acm-export.json", payload: "{...}" },
        response: { status: "success", count: 12, rows: [] },
      },
    ],
  }),
  "tenant-integrations-cloud-list": defineEndpoint("tenant-integrations-cloud-list", {
    method: "GET",
    path: "/tenant/integrations/cloud",
    summary: "List configured cloud integration connections.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "integrations", type: "object[]", required: true, description: "Cloud integration rows." }],
    examples: [{ label: "Cloud integrations", response: { status: "success", integrations: [] } }],
  }),
  "tenant-integrations-cloud-upsert": defineEndpoint("tenant-integrations-cloud-upsert", {
    method: "POST",
    path: "/tenant/integrations/cloud/{provider}",
    summary: "Create or update cloud integration credentials and connection settings.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "region", type: "string", required: false, description: "Cloud region." },
      { name: "vaultName", type: "string", required: false, description: "Azure Key Vault name." },
      { name: "roleArn", type: "string", required: false, description: "AWS IAM role ARN." },
      { name: "externalId", type: "string", required: false, description: "Optional external id for role assumption." },
      { name: "projectId", type: "string", required: false, description: "GCP project id." },
      { name: "credentialsJson", type: "string", required: false, description: "GCP credentials JSON string." },
      { name: "kubeconfigJson", type: "string", required: false, description: "Kubernetes kubeconfig content." },
      { name: "namespace", type: "string", required: false, description: "Kubernetes namespace filter." },
      { name: "context", type: "string", required: false, description: "Kubernetes context." },
      { name: "tenantId", type: "string", required: false, description: "Azure tenant id." },
      { name: "clientId", type: "string", required: false, description: "Azure client id." },
      { name: "clientSecret", type: "string", required: false, description: "Azure client secret." },
    ],
    responseFields: [{ name: "integration", type: "object", required: true, description: "Saved cloud integration row." }],
    examples: [
      {
        label: "Upsert AWS cloud integration",
        request: { region: "us-east-1", roleArn: "arn:aws:iam::123456789012:role/QtanglReadOnly" },
        response: { status: "success", integration: { provider: "aws", enabled: true } },
      },
    ],
  }),
  "tenant-integrations-cloud-test": defineEndpoint("tenant-integrations-cloud-test", {
    method: "POST",
    path: "/tenant/integrations/cloud/{provider}/test",
    summary: "Test configured cloud integration connectivity and sample inventory access.",
    auth: true,
    role: ROLE_WRITE,
    responseFields: [
      { name: "ok", type: "boolean", required: true, description: "Connectivity test result." },
      { name: "previewCount", type: "integer", required: false, description: "Number of preview rows discovered." },
      { name: "reason", type: "string", required: false, description: "Failure reason when test fails." },
    ],
    examples: [{ label: "Test AWS integration", response: { status: "success", ok: true, previewCount: 19 } }],
  }),
  "tenant-integrations-keyfactor": defineEndpoint("tenant-integrations-keyfactor", {
    method: "POST",
    path: "/tenant/integrations/keyfactor",
    summary: "Create or update Keyfactor integration credentials and collection scope.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "baseUrl", type: "string", required: true, description: "Keyfactor API base URL." },
      { name: "apiToken", type: "string", required: true, description: "Keyfactor API token." },
      { name: "collectionId", type: "string", required: false, description: "Optional Keyfactor collection filter." },
      { name: "writeBackEnabled", type: "boolean", required: false, default: "false", description: "Enable write-back actions." },
    ],
    responseFields: [{ name: "integration", type: "object", required: true, description: "Saved keyfactor integration config." }],
    examples: [
      {
        label: "Configure Keyfactor",
        request: { baseUrl: "https://keyfactor.example.com", apiToken: "kf_***" },
        response: { status: "success", integration: { provider: "keyfactor" } },
      },
    ],
  }),
  "tenant-integrations-keyfactor-test": defineEndpoint("tenant-integrations-keyfactor-test", {
    method: "POST",
    path: "/tenant/integrations/keyfactor/test",
    summary: "Validate Keyfactor connectivity by pulling a preview inventory sample.",
    auth: true,
    role: ROLE_WRITE,
    responseFields: [
      { name: "ok", type: "boolean", required: true, description: "Connectivity test result." },
      { name: "previewCount", type: "integer", required: false, description: "Preview record count." },
      { name: "message", type: "string", required: false, description: "Provider diagnostic message." },
    ],
    examples: [{ label: "Keyfactor test result", response: { status: "success", ok: true, previewCount: 8 } }],
  }),
  "tenant-integrations-clm-upsert": defineEndpoint("tenant-integrations-clm-upsert", {
    method: "POST",
    path: "/tenant/integrations/clm/{clm_provider}",
    summary: "Create or update CLM integration credentials for the selected CLM provider.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "apiKey", type: "string", required: false, description: "CLM API key." },
      { name: "host", type: "string", required: false, description: "CLM host URL." },
      { name: "token", type: "string", required: false, description: "CLM access token." },
      { name: "tenant", type: "string", required: false, description: "Provider-specific tenant identifier." },
    ],
    responseFields: [{ name: "integration", type: "object", required: true, description: "Saved CLM integration config." }],
    examples: [
      {
        label: "Configure CLM integration",
        request: { host: "https://clm.example.com", token: "clm_***" },
        response: { status: "success", integration: { provider: "clm-servicenow" } },
      },
    ],
  }),
  "tenant-integrations-clm-test": defineEndpoint("tenant-integrations-clm-test", {
    method: "POST",
    path: "/tenant/integrations/clm/{clm_provider}/test",
    summary: "Test CLM integration by executing a provider pull preview.",
    auth: true,
    role: ROLE_WRITE,
    responseFields: [
      { name: "ok", type: "boolean", required: true, description: "Connectivity and pull status." },
      { name: "previewCount", type: "integer", required: false, description: "Preview items count." },
      { name: "message", type: "string", required: false, description: "Provider diagnostic message." },
    ],
    examples: [{ label: "CLM test", response: { status: "success", ok: true, previewCount: 11 } }],
  }),
  "tenant-analytics-anomaly": defineEndpoint("tenant-analytics-anomaly", {
    method: "GET",
    path: "/tenant/analytics/anomaly",
    summary: "Detect anomalies in readiness score trends using recent scan history.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "alerts", type: "object[]", required: true, description: "Anomaly alerts and confidence scores." }],
    examples: [{ label: "Anomaly alerts", response: { status: "success", alerts: [] } }],
  }),
  "tenant-analytics-forecast": defineEndpoint("tenant-analytics-forecast", {
    method: "GET",
    path: "/tenant/analytics/forecast",
    summary: "Forecast readiness trend trajectory from recent scan score history.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "forecast", type: "object[]", required: false, description: "Projected readiness points." },
      { name: "confidence", type: "number", required: false, description: "Model confidence score." },
    ],
    examples: [{ label: "Readiness forecast", response: { status: "success", forecast: [{ t: "2026-07-01", score: 85 }] } }],
  }),
  "tenant-benchmarks": defineEndpoint("tenant-benchmarks", {
    method: "GET",
    path: "/tenant/benchmarks",
    summary: "Compare tenant readiness against industry benchmark cohorts.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "index", type: "object", required: true, description: "Industry benchmark index snapshot." },
      { name: "comparison", type: "object | null", required: false, description: "Tenant-vs-cohort comparison metrics." },
      { name: "benchmarkOptIn", type: "boolean", required: true, description: "Whether tenant has opted into benchmarks." },
    ],
    examples: [{ label: "Benchmark comparison", response: { status: "success", benchmarkOptIn: true, comparison: { percentile: 74 } } }],
  }),
  "tenant-drift-intel": defineEndpoint("tenant-drift-intel", {
    method: "GET",
    path: "/tenant/drift-intel",
    summary: "Return cohort drift intelligence when benchmark opt-in data is available.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "available", type: "boolean", required: true, description: "Whether drift data is available." },
      { name: "reason", type: "string", required: false, description: "Unavailable reason when available=false." },
      { name: "metrics", type: "object", required: false, description: "Drift aggregate metrics." },
    ],
    examples: [{ label: "Drift available", response: { status: "success", available: true, industry: "financial", metrics: {} } }],
  }),
  "tenant-compliance-posture": defineEndpoint("tenant-compliance-posture", {
    method: "GET",
    path: "/tenant/compliance/posture",
    summary: "Map scan findings to compliance frameworks for posture reporting.",
    auth: true,
    role: ROLE_ANY,
    queryParams: [scanIdParam],
    responseFields: [{ name: "frameworks", type: "object", required: true, description: "Framework mappings and coverage stats." }],
    examples: [{ label: "Compliance posture", response: { status: "success", frameworks: { soc2: { coveragePct: 91 } } } }],
  }),
  "tenant-evidence-vault": defineEndpoint("tenant-evidence-vault", {
    method: "GET",
    path: "/tenant/evidence",
    summary: "Summarize retained evidence-vault objects and retention horizon.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "total", type: "integer", required: true, description: "Total retained objects." },
      { name: "active", type: "integer", required: true, description: "Objects still within retention." },
      { name: "objects", type: "object[]", required: true, description: "Retained evidence records." },
    ],
    examples: [{ label: "Evidence vault summary", response: { status: "success", total: 4, active: 4, objects: [] } }],
  }),
  "tenant-evidence-retain": defineEndpoint("tenant-evidence-retain", {
    method: "POST",
    path: "/tenant/evidence/{scan_id}/retain",
    summary: "Retain a scan's evidence package in the tenant evidence vault.",
    auth: true,
    role: ROLE_WRITE,
    responseFields: [
      { name: "retained", type: "boolean", required: true, description: "Whether retention succeeded." },
      { name: "retainedUntil", type: "string (ISO8601)", required: false, description: "Retention expiry date." },
    ],
    examples: [{ label: "Retain evidence", response: { status: "success", retained: true, retainedUntil: "2027-06-09T00:00:00Z" } }],
  }),
  "tenant-billing-portal": defineEndpoint("tenant-billing-portal", {
    method: "GET",
    path: "/tenant/billing/portal",
    summary: "Return Stripe billing portal URL and entitlement context when configured.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "configured", type: "boolean", required: true, description: "Whether billing integration is configured." },
      { name: "portalUrl", type: "string | null", required: false, description: "Self-serve billing portal URL." },
      { name: "entitlements", type: "object", required: false, description: "Tenant billing entitlements." },
    ],
    examples: [{ label: "Billing portal", response: { status: "success", configured: true, portalUrl: "https://billing.stripe.com/p/session_..." } }],
  }),
  "tenant-oidc-get": defineEndpoint("tenant-oidc-get", {
    method: "GET",
    path: "/tenant/oidc",
    summary: "Get current tenant OIDC SSO configuration.",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [{ name: "oidc", type: "object", required: true, description: "OIDC config including issuer and client id." }],
    examples: [{ label: "OIDC config", response: { status: "success", oidc: { issuerUrl: "https://idp.example.com", enabled: true } } }],
  }),
  "tenant-oidc-put": defineEndpoint("tenant-oidc-put", {
    method: "PUT",
    path: "/tenant/oidc",
    summary: "Create or update tenant OIDC SSO configuration.",
    auth: true,
    role: ROLE_ADMIN,
    requestFields: [
      { name: "issuerUrl", type: "string", required: true, description: "OIDC issuer URL." },
      { name: "clientId", type: "string", required: true, description: "OIDC client id." },
      { name: "clientSecret", type: "string", required: false, description: "OIDC client secret." },
      { name: "enabled", type: "boolean", required: false, default: "false", description: "Enable OIDC auth for tenant." },
    ],
    responseFields: [{ name: "oidc", type: "object", required: true, description: "Saved OIDC config." }],
    examples: [
      {
        label: "Enable OIDC",
        request: { issuerUrl: "https://idp.example.com", clientId: "qtangl-web", clientSecret: "secret", enabled: true },
        response: { status: "success", oidc: { enabled: true } },
      },
    ],
  }),
  "tenant-data-delete": defineEndpoint("tenant-data-delete", {
    method: "DELETE",
    path: "/tenant/data",
    summary: "Delete all tenant data for retention/offboarding workflows.",
    auth: true,
    role: ROLE_WRITE,
    responseFields: [
      { name: "deletedScans", type: "integer", required: false, description: "Count of deleted scan records." },
      { name: "deletedAudit", type: "integer", required: false, description: "Count of deleted audit entries." },
    ],
    examples: [{ label: "Delete tenant data", response: { status: "success", deletedScans: 24, deletedAudit: 400 } }],
  }),
  "tenant-offboard": defineEndpoint("tenant-offboard", {
    method: "POST",
    path: "/tenant/offboard",
    summary: "Admin-only alias endpoint to offboard and purge tenant data.",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [
      { name: "deletedScans", type: "integer", required: false, description: "Count of deleted scan records." },
      { name: "deletedAudit", type: "integer", required: false, description: "Count of deleted audit entries." },
    ],
    examples: [{ label: "Admin offboard", response: { status: "success", deletedScans: 24, deletedAudit: 400 } }],
  }),
  "tenant-coverage-code-scan": defineEndpoint("tenant-coverage-code-scan", {
    method: "POST",
    path: "/tenant/coverage/code-scan",
    summary: "Scan source snippets or GitHub repositories for crypto-coverage findings.",
    auth: true,
    role: ROLE_ANY,
    requestFields: [
      { name: "content", type: "string", required: false, description: "Source snippet text to scan." },
      { name: "path", type: "string", required: false, default: "upload", description: "Logical file path for snippet analysis." },
      { name: "githubOwner", type: "string", required: false, description: "GitHub repository owner." },
      { name: "githubRepo", type: "string", required: false, description: "GitHub repository name." },
      { name: "githubToken", type: "string", required: false, description: "GitHub token for repository access." },
      { name: "ref", type: "string", required: false, default: "HEAD", description: "Git revision/ref to scan." },
    ],
    responseFields: [{ name: "findings", type: "object[]", required: false, description: "Coverage findings list for snippet mode." }],
    examples: [
      {
        label: "Scan snippet",
        request: { path: "tls/client.ts", content: "createCipheriv('aes-128-cbc', ...)" },
        response: { status: "success", findings: [{ id: "f_001", severity: "medium" }] },
      },
    ],
  }),
  "tenant-coverage-cloud": defineEndpoint("tenant-coverage-cloud", {
    method: "GET",
    path: "/tenant/coverage/cloud/{provider}",
    summary: "Run cloud coverage preview for provider and return preview object count.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "provider", type: "string", required: true, description: "Requested cloud provider." },
      { name: "previewCount", type: "integer", required: true, description: "Preview object count." },
    ],
    examples: [{ label: "Cloud coverage preview", response: { status: "success", provider: "aws", previewCount: 42 } }],
  }),
  "tenant-ai-explain": defineEndpoint("tenant-ai-explain", {
    method: "POST",
    path: "/tenant/ai/explain",
    summary: "Generate AI explanation for a finding with optional context.",
    auth: true,
    role: ROLE_ANY,
    requestFields: [
      { name: "finding", type: "object", required: false, description: "Finding payload to explain." },
      { name: "context", type: "string", required: false, description: "Extra context to tailor explanation." },
    ],
    responseFields: [
      { name: "summary", type: "string", required: false, description: "High-level explanation." },
      { name: "impact", type: "string", required: false, description: "Business/security impact summary." },
      { name: "nextSteps", type: "string[]", required: false, description: "Suggested remediation actions." },
    ],
    examples: [
      {
        label: "Explain finding",
        request: { finding: { id: "f_001", title: "RSA-1024 certificate" }, context: "external API edge" },
        response: { status: "success", summary: "RSA-1024 is below policy baseline.", nextSteps: ["Rotate certificate"] },
      },
    ],
  }),
  "tenant-dashboard-summary": defineEndpoint("tenant-dashboard-summary", {
    method: "GET",
    path: "/tenant/dashboard/summary",
    summary: "Aggregate dashboard payload: KPIs, trends, alerts, recommendations, and coaching state.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [
      { name: "kpis", type: "object", required: true, description: "Readiness and scan KPI snapshot." },
      { name: "trend", type: "object[]", required: true, description: "Recent readiness trend points." },
      { name: "recommendations", type: "object[]", required: true, description: "Role-aware dashboard recommendations." },
    ],
    examples: [{ label: "Dashboard summary", response: { status: "success", kpis: {}, trend: [] } }],
  }),
  "tenant-dashboard-tab": defineEndpoint("tenant-dashboard-tab", {
    method: "GET",
    path: "/tenant/dashboard/tab/{tab_name}",
    summary: "Lazy-load a single dashboard tab payload (evidence, monitor, convert, etc.).",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "tab", type: "string", required: true, description: "Requested tab name." }],
    examples: [{ label: "Evidence tab", response: { status: "success", tab: "evidence" } }],
  }),
  "tenant-dashboard-events": defineEndpoint("tenant-dashboard-events", {
    method: "GET",
    path: "/tenant/dashboard/events",
    summary: "Server-sent style event feed for dashboard activity (scans, schedules, integrations).",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "events", type: "object[]", required: true, description: "Recent tenant events." }],
    examples: [{ label: "Recent events", response: { status: "success", events: [] } }],
  }),
  "tenant-dashboard-recommendations": defineEndpoint("tenant-dashboard-recommendations", {
    method: "GET",
    path: "/tenant/dashboard/recommendations",
    summary: "List actionable dashboard recommendations for the current role.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "recommendations", type: "object[]", required: true, description: "Recommendation cards." }],
    examples: [{ label: "Recommendations", response: { status: "success", recommendations: [] } }],
  }),
  "tenant-dashboard-digest-preview": defineEndpoint("tenant-dashboard-digest-preview", {
    method: "POST",
    path: "/tenant/dashboard/digest/preview",
    summary: "Render executive digest HTML/text preview without sending email.",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [{ name: "preview", type: "object", required: true, description: "Digest preview body and metadata." }],
    examples: [{ label: "Preview digest", response: { status: "success", preview: { subject: "Weekly readiness" } } }],
  }),
  "tenant-dashboard-digest-send-test": defineEndpoint("tenant-dashboard-digest-send-test", {
    method: "POST",
    path: "/tenant/dashboard/digest/send-test",
    summary: "Send a test executive digest email to an admin-specified recipient.",
    auth: true,
    role: ROLE_ADMIN,
    requestFields: [{ name: "email", type: "string", required: false, description: "Override recipient; defaults to caller." }],
    responseFields: [{ name: "sent", type: "boolean", required: true, description: "Whether dispatch succeeded." }],
    examples: [{ label: "Send test digest", request: { email: "ciso@example.com" }, response: { status: "success", sent: true } }],
  }),
  "tenant-analytics-readiness-trend": defineEndpoint("tenant-analytics-readiness-trend", {
    method: "GET",
    path: "/tenant/analytics/readiness-trend",
    summary: "Historical readiness score trend for analytics charts.",
    auth: true,
    role: ROLE_ANY,
    queryParams: [{ name: "limit", type: "integer", required: false, default: "30", description: "Max data points." }],
    responseFields: [{ name: "points", type: "object[]", required: true, description: "Trend series." }],
    examples: [{ label: "Trend", response: { status: "success", points: [] } }],
  }),
  "tenant-analytics-track": defineEndpoint("tenant-analytics-track", {
    method: "POST",
    path: "/tenant/analytics/track",
    summary: "Record product analytics events from the dashboard (feature usage, funnels).",
    auth: true,
    role: ROLE_ANY,
    requestFields: [
      { name: "event", type: "string", required: true, description: "Event name." },
      { name: "properties", type: "object", required: false, description: "Optional event properties." },
    ],
    responseFields: [{ name: "tracked", type: "boolean", required: true, description: "Whether event was accepted." }],
    examples: [{ label: "Track event", request: { event: "report_downloaded" }, response: { status: "success", tracked: true } }],
  }),
  "tenant-scans-bulk-export": defineEndpoint("tenant-scans-bulk-export", {
    method: "POST",
    path: "/tenant/scans/bulk-export",
    summary: "Export multiple scans as a ZIP bundle of reports and metadata.",
    auth: true,
    role: ROLE_ANY,
    requestFields: [
      { name: "scanIds", type: "string[]", required: true, description: "Scan ids to include." },
      { name: "format", type: "string", required: false, default: "pdf", description: "Report format per scan." },
    ],
    responseFields: [{ name: "downloadUrl", type: "string", required: false, description: "Signed download URL when async." }],
    examples: [{ label: "Bulk export", request: { scanIds: ["scan_001"] }, response: { status: "success" } }],
  }),
  "tenant-scans-batch": defineEndpoint("tenant-scans-batch", {
    method: "POST",
    path: "/tenant/scans/batch",
    summary: "Start live baseline scans for multiple authorized domains.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "domains", type: "string[]", required: false, description: "Subset to scan; defaults to full allowlist." },
      { name: "industry", type: "string", required: false, description: "Industry for peer comparison." },
      { name: "depth", type: "string", required: false, default: "standard", description: "Scan depth." },
      { name: "createSchedules", type: "boolean", required: false, description: "Also create monitor schedules." },
      { name: "scheduleCadenceHours", type: "number", required: false, description: "Cadence when createSchedules is true." },
    ],
    examples: [
      {
        label: "Batch scan",
        request: { domains: ["qtangl.com", "api.qtangl.com"], industry: "general" },
        response: { status: "success", count: 2, scans: [{ scanId: "scan-abc", target: "qtangl.com", status: "running" }] },
      },
    ],
  }),
  "tenant-schedules-batch": defineEndpoint("tenant-schedules-batch", {
    method: "POST",
    path: "/tenant/schedules/batch",
    summary: "Create monitor schedules for multiple authorized targets.",
    auth: true,
    role: ROLE_WRITE,
    requestFields: [
      { name: "targets", type: "string[]", required: false, description: "Domains to schedule; defaults to allowlist." },
      { name: "cadenceHours", type: "number", required: false, default: "168", description: "Hours between runs." },
      { name: "skipExisting", type: "boolean", required: false, description: "Skip targets that already have schedules." },
    ],
    examples: [
      {
        label: "Batch schedules",
        request: { targets: ["qtangl.com", "api.qtangl.com"], cadenceHours: 168 },
        response: { status: "success", count: 2, schedules: [{ id: "sched-1", target: "qtangl.com" }] },
      },
    ],
  }),
  "tenant-api-keys-list": defineEndpoint("tenant-api-keys-list", {
    method: "GET",
    path: "/tenant/api-keys",
    summary: "List tenant API keys (metadata only; secrets shown once at creation).",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [{ name: "keys", type: "object[]", required: true, description: "Key metadata rows." }],
    examples: [{ label: "List keys", response: { status: "success", keys: [] } }],
  }),
  "tenant-api-keys-create": defineEndpoint("tenant-api-keys-create", {
    method: "POST",
    path: "/tenant/api-keys",
    summary: "Create a new tenant API key with scoped roles.",
    auth: true,
    role: ROLE_ADMIN,
    requestFields: [{ name: "label", type: "string", required: false, description: "Human-readable key label." }],
    responseFields: [{ name: "key", type: "string", required: true, description: "Plaintext key (shown once)." }],
    examples: [{ label: "Create key", request: { label: "CI pipeline" }, response: { status: "success", key: "qtangl_…" } }],
  }),
  "tenant-api-keys-delete": defineEndpoint("tenant-api-keys-delete", {
    method: "DELETE",
    path: "/tenant/api-keys/{key_id}",
    summary: "Revoke a tenant API key by id.",
    auth: true,
    role: ROLE_ADMIN,
    examples: [{ label: "Revoke key", response: { status: "success", revoked: true } }],
  }),
  "tenant-members-list": defineEndpoint("tenant-members-list", {
    method: "GET",
    path: "/tenant/members",
    summary: "List tenant members and roles.",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [{ name: "members", type: "object[]", required: true, description: "Membership rows." }],
    examples: [{ label: "List members", response: { status: "success", members: [] } }],
  }),
  "tenant-members-patch": defineEndpoint("tenant-members-patch", {
    method: "PATCH",
    path: "/tenant/members/{membership_id}",
    summary: "Update a member role.",
    auth: true,
    role: ROLE_ADMIN,
    requestFields: [{ name: "role", type: "string", required: true, description: "New role: viewer, operator, or admin." }],
    examples: [{ label: "Change role", request: { role: "operator" }, response: { status: "success" } }],
  }),
  "tenant-members-delete": defineEndpoint("tenant-members-delete", {
    method: "DELETE",
    path: "/tenant/members/{membership_id}",
    summary: "Remove a member from the tenant.",
    auth: true,
    role: ROLE_ADMIN,
    examples: [{ label: "Remove member", response: { status: "success" } }],
  }),
  "tenant-invites-list": defineEndpoint("tenant-invites-list", {
    method: "GET",
    path: "/tenant/invites",
    summary: "List pending team invites.",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [{ name: "invites", type: "object[]", required: true, description: "Pending invites." }],
    examples: [{ label: "List invites", response: { status: "success", invites: [] } }],
  }),
  "tenant-invites-create": defineEndpoint("tenant-invites-create", {
    method: "POST",
    path: "/tenant/invites",
    summary: "Invite a user by email with a role.",
    auth: true,
    role: ROLE_ADMIN,
    requestFields: [
      { name: "email", type: "string", required: true, description: "Invitee email." },
      { name: "role", type: "string", required: false, default: "operator", description: "Assigned role." },
    ],
    examples: [{ label: "Send invite", request: { email: "alice@example.com" }, response: { status: "success" } }],
  }),
  "tenant-invites-delete": defineEndpoint("tenant-invites-delete", {
    method: "DELETE",
    path: "/tenant/invites/{invite_id}",
    summary: "Cancel a pending invite.",
    auth: true,
    role: ROLE_ADMIN,
    examples: [{ label: "Cancel invite", response: { status: "success" } }],
  }),
  "tenant-sso-portal-link": defineEndpoint("tenant-sso-portal-link", {
    method: "POST",
    path: "/tenant/sso/portal-link",
    summary: "Generate a WorkOS Admin Portal link for SSO configuration.",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [{ name: "url", type: "string", required: true, description: "Time-limited portal URL." }],
    examples: [{ label: "Portal link", response: { status: "success", url: "https://…" } }],
  }),
  "tenant-workspace-patch": defineEndpoint("tenant-workspace-patch", {
    method: "PATCH",
    path: "/tenant/workspace",
    summary: "Update workspace display name and slug.",
    auth: true,
    role: ROLE_ADMIN,
    requestFields: [{ name: "displayName", type: "string", required: false, description: "Workspace display name." }],
    examples: [{ label: "Rename workspace", request: { displayName: "Acme Security" }, response: { status: "success" } }],
  }),
  "tenant-authorized-domains-list": defineEndpoint("tenant-authorized-domains-list", {
    method: "GET",
    path: "/tenant/authorized-domains",
    summary: "List email domains authorized for team invites.",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [{ name: "domains", type: "string[]", required: true, description: "Authorized domains." }],
    examples: [{ label: "List domains", response: { status: "success", domains: ["example.com"] } }],
  }),
  "tenant-authorized-domains-create": defineEndpoint("tenant-authorized-domains-create", {
    method: "POST",
    path: "/tenant/authorized-domains",
    summary: "Replace the full authorized scan domain list.",
    auth: true,
    role: ROLE_ADMIN,
    requestFields: [
      { name: "domains", type: "string[]", required: true, description: "Authorized domains." },
      { name: "attestation", type: "string", required: true, description: "Authorization attestation." },
    ],
    examples: [{ label: "Replace list", request: { domains: ["example.com"], attestation: "I am authorized…" }, response: { status: "success" } }],
  }),
  "tenant-authorized-domains-patch": defineEndpoint("tenant-authorized-domains-patch", {
    method: "PATCH",
    path: "/tenant/authorized-domains",
    summary: "Add or remove a single authorized scan domain.",
    auth: true,
    role: ROLE_ADMIN,
    requestFields: [
      { name: "action", type: "string", required: true, description: "add or remove" },
      { name: "domain", type: "string", required: true, description: "Domain to add or remove." },
      { name: "attestation", type: "string", required: false, description: "Required when action is add." },
    ],
    examples: [{ label: "Add domain", request: { action: "add", domain: "api.example.com", attestation: "I am authorized…" }, response: { status: "success" } }],
  }),
  "tenant-onboarding-patch": defineEndpoint("tenant-onboarding-patch", {
    method: "PATCH",
    path: "/tenant/onboarding",
    summary: "Update onboarding checklist progress and dismissed banners.",
    auth: true,
    role: ROLE_ANY,
    requestFields: [{ name: "step", type: "string", required: false, description: "Completed onboarding step id." }],
    examples: [{ label: "Complete step", request: { step: "first_scan" }, response: { status: "success" } }],
  }),
  "tenant-billing-checkout": defineEndpoint("tenant-billing-checkout", {
    method: "POST",
    path: "/tenant/billing/checkout",
    summary: "Create a Stripe Checkout session for plan upgrade.",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [{ name: "url", type: "string", required: true, description: "Stripe Checkout URL." }],
    examples: [{ label: "Checkout", response: { status: "success", url: "https://checkout.stripe.com/…" } }],
  }),
  "tenant-billing-portal-post": defineEndpoint("tenant-billing-portal-post", {
    method: "POST",
    path: "/tenant/billing/portal",
    summary: "Create a Stripe Customer Portal session.",
    auth: true,
    role: ROLE_ADMIN,
    responseFields: [{ name: "url", type: "string", required: true, description: "Portal session URL." }],
    examples: [{ label: "Portal session", response: { status: "success", url: "https://billing.stripe.com/…" } }],
  }),
  "tenant-legal-accept": defineEndpoint("tenant-legal-accept", {
    method: "POST",
    path: "/tenant/legal/accept",
    summary: "Record acceptance of terms of service and privacy policy.",
    auth: true,
    role: ROLE_ADMIN,
    requestFields: [{ name: "version", type: "string", required: true, description: "Legal document version accepted." }],
    examples: [{ label: "Accept terms", request: { version: "2026-06-01" }, response: { status: "success" } }],
  }),
  "tenant-alerts-read": defineEndpoint("tenant-alerts-read", {
    method: "PATCH",
    path: "/tenant/alerts/{alert_id}/read",
    summary: "Mark a dashboard alert as read.",
    auth: true,
    role: ROLE_ANY,
    examples: [{ label: "Mark read", response: { status: "success" } }],
  }),
  "tenant-alerts-read-all": defineEndpoint("tenant-alerts-read-all", {
    method: "POST",
    path: "/tenant/alerts/read-all",
    summary: "Mark all dashboard alerts as read for the current user.",
    auth: true,
    role: ROLE_ANY,
    examples: [{ label: "Mark all read", response: { status: "success" } }],
  }),
  "tenant-recommendations-dismiss": defineEndpoint("tenant-recommendations-dismiss", {
    method: "POST",
    path: "/tenant/recommendations/{recommendation_id}/dismiss",
    summary: "Dismiss a dashboard recommendation card.",
    auth: true,
    role: ROLE_ANY,
    examples: [{ label: "Dismiss", response: { status: "success" } }],
  }),
  "tenant-ai-explain-scan": defineEndpoint("tenant-ai-explain-scan", {
    method: "POST",
    path: "/tenant/ai/explain-scan",
    summary: "Generate AI narrative summary for an entire scan.",
    auth: true,
    role: ROLE_ANY,
    requestFields: [{ name: "scanId", type: "string", required: true, description: "Scan to summarize." }],
    examples: [{ label: "Explain scan", request: { scanId: "scan_001" }, response: { status: "success", summary: "…" } }],
  }),
  "tenant-ai-explain-portfolio": defineEndpoint("tenant-ai-explain-portfolio", {
    method: "POST",
    path: "/tenant/ai/explain-portfolio",
    summary: "Generate AI executive summary across portfolio tenants.",
    auth: true,
    role: ROLE_ANY,
    examples: [{ label: "Explain portfolio", response: { status: "success", summary: "…" } }],
  }),
  "tenant-partner-portfolio-summary": defineEndpoint("tenant-partner-portfolio-summary", {
    method: "GET",
    path: "/tenant/partner/portfolio-summary",
    summary: "MSSP partner rollup of child tenant readiness posture.",
    auth: true,
    role: ROLE_ANY,
    responseFields: [{ name: "children", type: "object[]", required: true, description: "Per-child summary rows." }],
    examples: [{ label: "Portfolio summary", response: { status: "success", children: [] } }],
  }),
};
