import type { Metadata } from "next";
import Link from "next/link";

import PageHero from "@/components/layout/PageHero";
import PageShell from "@/components/layout/PageShell";
import Section from "@/components/layout/Section";
import Card from "@/components/ui/Card";
import { hospitalMethodologyCopy } from "@/lib/copy/methodology";

export const metadata: Metadata = {
  title: "Hospital demo methodology",
  description:
    "See the sources, solver settings, evidence files, and QPU trace details behind the hospital re-staffing demo.",
};

export default function HospitalMethodologyPage() {
  return (
    <PageShell>
      <PageHero
        eyebrow={hospitalMethodologyCopy.eyebrow}
        title={hospitalMethodologyCopy.title}
        description={hospitalMethodologyCopy.description}
        actions={[
          { href: "/demo/hospital", label: "Open the demo" },
          { href: "/access?source=methodology", label: "Request pilot access", variant: "secondary" },
        ]}
      />
      <Section gap="tight" className="pb-0">
        <div className="grid gap-6 lg:grid-cols-3">
          <Card tone="strong" className="rounded-[var(--radius-xl)]">
            <h2 className="text-xl font-semibold text-white">Sources</h2>
            <ul className="mt-4 space-y-3 text-sm leading-7 text-[var(--color-gray-300)]">
              {hospitalMethodologyCopy.sources.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </Card>
          <Card tone="strong" className="rounded-[var(--radius-xl)]">
            <h2 className="text-xl font-semibold text-white">{hospitalMethodologyCopy.solver.title}</h2>
            <ul className="mt-4 space-y-3 text-sm leading-7 text-[var(--color-gray-300)]">
              {hospitalMethodologyCopy.solver.items.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </Card>
          <Card tone="strong" className="rounded-[var(--radius-xl)]">
            <h2 className="text-xl font-semibold text-white">{hospitalMethodologyCopy.evidence.title}</h2>
            <ul className="mt-4 space-y-3 text-sm leading-7 text-[var(--color-gray-300)]">
              {hospitalMethodologyCopy.evidence.items.map((item) => (
                <li key={item}>
                  <code>{item}</code>
                </li>
              ))}
            </ul>
          </Card>
        </div>
        <Card tone="feature" className="mt-6 rounded-[var(--radius-feature)]">
          <h2 className="text-2xl font-semibold text-white">Cached QPU trace</h2>
          <p className="mt-4 text-sm leading-7 text-[var(--color-gray-300)]">
            The hospital demo replays the cath-lab QPU trace from{" "}
            <code>demos/hospital_restaffing/data/qpu_trace.json</code>. That keeps the page recording-safe
            while preserving a hardware-backed audit artifact.
          </p>
          <p className="mt-4 text-sm leading-7 text-[var(--color-gray-300)]">
            The benchmark evidence is generated by <code>backend/benchmarks/hospital_harness.py</code> and
            written to <code>benchmarks/hospital_results.csv</code>.
          </p>
          <div className="mt-5">
            <Link
              href="/demo/hospital"
              className="inline-flex rounded-full border border-[var(--border)] px-4 py-2 text-sm text-white transition hover:border-[var(--border-strong)] hover:bg-white/[0.04]"
            >
              Back to the demo
            </Link>
          </div>
        </Card>
      </Section>
    </PageShell>
  );
}
