import {
  apiPreviewRequest,
  apiPreviewResponse,
  docsQuickstartRequest,
  docsQuickstartResponse,
} from "@/lib/copy/api-examples";

import type { DocsEndpoint } from "@/lib/docs/types";

const optimizeRequestFields = [
  {
    name: "type",
    type: "string",
    required: true,
    description: "Problem family: schedule, scheduling (alias), routing, or allocation.",
    example: "schedule",
  },
  {
    name: "tasks[]",
    type: "ScheduleTaskInput[]",
    required: false,
    description: "Work items for scheduling problems.",
    example: '{ "id": "A", "duration": 3, "crew": "Crew A" }',
  },
  {
    name: "constraints[]",
    type: "string[]",
    required: false,
    description: "Hard rules the plan must satisfy (dependencies, blocked windows).",
    example: '"A must happen before B"',
  },
  {
    name: "stops[]",
    type: "RoutingStopInput[]",
    required: false,
    description: "Stops for routing problems.",
    example: '{ "id": "hospital", "serviceWindow": "08:30-10:00" }',
  },
  {
    name: "vehicles[]",
    type: "VehicleInput[]",
    required: false,
    description: "Fleet units and capacity for routing.",
  },
  {
    name: "shifts[]",
    type: "ShiftInput[]",
    required: false,
    description: "Shifts to cover for allocation problems.",
  },
  {
    name: "staff[]",
    type: "StaffInput[]",
    required: false,
    description: "People, skills, and hour limits for allocation.",
  },
  {
    name: "data",
    type: "object",
    required: false,
    description: "Extension bag for forward-compatible fields.",
    example: "{}",
  },
] as const;

const optimizeResponseFields = [
  {
    name: "status",
    type: '"success"',
    required: true,
    description: "Job completed with a feasible plan.",
  },
  {
    name: "summary",
    type: "string",
    required: true,
    description: "Plain-English explanation for operators.",
  },
  {
    name: "solution",
    type: "array | object",
    required: true,
    description: "Executable plan: task timeline, route assignments, or staffing grid.",
  },
  {
    name: "metrics",
    type: "object",
    required: true,
    description: "constraintViolations, savingsEstimate, and problem-specific KPIs.",
  },
  {
    name: "method",
    type: '"classical" | "hybrid"',
    required: true,
    description: "Honest solver path label.",
  },
  {
    name: "details",
    type: "object",
    required: true,
    description: "solver, backend, and diagnostics for engineering review.",
  },
  {
    name: "visualization",
    type: "object | null",
    required: false,
    description: "Optional UI-friendly timeline or grid payload.",
  },
] as const;

export const docsEndpoints: Record<string, DocsEndpoint> = {
  optimize: {
    id: "optimize",
    method: "POST",
    path: "/optimize",
    status: "ga",
    title: "POST /optimize",
    summary:
      "Submit a schedule, route, or staffing problem and receive a ranked plan with summary, metrics, and method details.",
    auth: true,
    rateLimit: "300 requests per minute per API key (default)",
    requestFields: [...optimizeRequestFields],
    responseFields: [...optimizeResponseFields],
    errors: [401, 422, 429, 500, 501],
    examples: [
      {
        label: "Quickstart schedule",
        request: docsQuickstartRequest,
        response: docsQuickstartResponse,
      },
      {
        label: "Construction schedule",
        request: apiPreviewRequest,
        response: apiPreviewResponse,
      },
    ],
    notes: [
      "Live solver path: schedule only. Routing and allocation return 501 until parsers and solvers ship.",
      "Classical CP-SAT baseline runs on every schedule job. Hybrid QAOA is bounded and optional.",
    ],
  },
  health: {
    id: "health",
    method: "GET",
    path: "/health",
    status: "ga",
    title: "GET /health",
    summary: "Liveness probe for uptime monitors and deployment readiness checks.",
    auth: false,
    responseFields: [
      {
        name: "status",
        type: '"ok"',
        required: true,
        description: "Service is accepting traffic.",
      },
    ],
    examples: [
      {
        label: "Health check",
        response: { status: "ok" },
      },
    ],
  },
  "hospital-roster": {
    id: "hospital-roster",
    method: "GET",
    path: "/hospital/roster",
    status: "pilot",
    title: "GET /hospital/roster",
    summary: "Load the bundled hospital roster fixture for the re-staffing demo.",
    auth: true,
    responseFields: [
      {
        name: "roster",
        type: "NurseRecord[]",
        required: true,
        description: "Nurses with skills, certifications, and availability metadata.",
      },
    ],
    examples: [
      {
        label: "Fixture roster",
        response: { status: "success", summary: "Hospital roster fixture loaded.", roster: [] },
      },
    ],
  },
  "hospital-scenarios": {
    id: "hospital-scenarios",
    method: "GET",
    path: "/hospital/scenarios",
    status: "pilot",
    title: "GET /hospital/scenarios",
    summary: "List available call-out scenarios for the hospital demo.",
    auth: true,
    responseFields: [
      {
        name: "scenarios",
        type: "Scenario[]",
        required: true,
        description: "Scenario id, title, and call-out metadata.",
      },
    ],
    examples: [
      {
        label: "Scenario catalog",
        response: { status: "success", scenarios: [] },
      },
    ],
  },
  "hospital-callout": {
    id: "hospital-callout",
    method: "GET",
    path: "/hospital/callout",
    status: "pilot",
    title: "GET /hospital/callout",
    summary: "Fetch a scenario call-out event by scenarioId query parameter.",
    auth: true,
    queryParams: [
      {
        name: "scenarioId",
        type: "string",
        required: false,
        default: "callout-cath-acls",
        description: "Scenario identifier from /hospital/scenarios.",
      },
    ],
    responseFields: [
      {
        name: "callOut",
        type: "CallOutEvent",
        required: true,
        description: "Nurse call-out details for the selected scenario.",
      },
    ],
    examples: [
      {
        label: "Default scenario",
        response: { status: "success", callOut: {}, scenario: {} },
      },
    ],
  },
  "hospital-qpu-trace": {
    id: "hospital-qpu-trace",
    method: "GET",
    path: "/hospital/qpu-trace",
    status: "pilot",
    title: "GET /hospital/qpu-trace",
    summary: "Return cached QPU trace metadata for hybrid audit storytelling in the demo.",
    auth: true,
    responseFields: [
      {
        name: "trace",
        type: "QpuTrace",
        required: true,
        description: "Simulator or hardware trace replay for the scoreboard.",
      },
    ],
    examples: [
      {
        label: "Trace replay",
        response: { status: "success", trace: {} },
      },
    ],
  },
  "hospital-upload-roster": {
    id: "hospital-upload-roster",
    method: "POST",
    path: "/hospital/upload-roster",
    status: "pilot",
    title: "POST /hospital/upload-roster",
    summary: "Upload a CSV roster and receive a 24-hour session id for solves.",
    auth: true,
    requestFields: [
      {
        name: "file",
        type: "multipart/form-data (CSV)",
        required: true,
        description: "Roster CSV matching the template columns in the hospital guide.",
      },
    ],
    responseFields: [
      {
        name: "sessionId",
        type: "string",
        required: true,
        description: "Pass as rosterSessionId on /hospital/callout/solve.",
      },
    ],
    examples: [
      {
        label: "Upload response",
        response: {
          status: "success",
          sessionId: "sess_…",
          summary: "Validated 42 nurses and stored the roster in a 24-hour session.",
        },
      },
    ],
  },
  "hospital-callout-solve": {
    id: "hospital-callout-solve",
    method: "POST",
    path: "/hospital/callout/solve",
    status: "pilot",
    title: "POST /hospital/callout/solve",
    summary:
      "Run the hospital re-staffing pipeline: classical baseline, hybrid audit, scoreboard, and timeline.",
    auth: true,
    requestFields: [
      {
        name: "scenarioId",
        type: "string",
        required: false,
        default: "callout-cath-acls",
        description: "Scenario to simulate.",
      },
      {
        name: "useFixture",
        type: "boolean",
        required: false,
        default: "true",
        description: "Use bundled fixture data when true.",
      },
      {
        name: "rosterSessionId",
        type: "string",
        required: false,
        description: "Session from upload-roster; overrides fixture roster when set.",
      },
      {
        name: "seed",
        type: "integer",
        required: false,
        default: "1234",
        description: "Reproducibility seed for research comparisons.",
      },
    ],
    responseFields: [
      {
        name: "scoreboard",
        type: "Scoreboard",
        required: true,
        description: "Buyer-facing KPIs and method comparison.",
      },
      {
        name: "classicalCandidate",
        type: "CandidatePlan",
        required: true,
        description: "CP-SAT baseline plan.",
      },
      {
        name: "hybridCandidates",
        type: "CandidatePlan[]",
        required: true,
        description: "Bounded QAOA alternates when eligible.",
      },
      {
        name: "auditPacks",
        type: "AuditPack[]",
        required: true,
        description: "Traceable decision artifacts.",
      },
    ],
    examples: [
      {
        label: "Solve payload",
        request: {
          scenarioId: "callout-cath-acls",
          useFixture: true,
          seed: 1234,
        },
        response: {
          status: "success",
          scoreboard: {},
          classicalCandidate: {},
          hybridCandidates: [],
        },
      },
    ],
  },
  "airline-network": {
    id: "airline-network",
    method: "GET",
    path: "/airline/network",
    status: "pilot",
    title: "GET /airline/network",
    summary: "Load the bundled airline network fixture (crew, flights, aircraft).",
    auth: true,
    responseFields: [
      { name: "crew", type: "CrewMember[]", required: true, description: "Crew roster." },
      { name: "flights", type: "FlightLeg[]", required: true, description: "Scheduled legs." },
      { name: "aircraft", type: "Aircraft[]", required: true, description: "Fleet tails." },
    ],
    examples: [
      {
        label: "Network fixture",
        response: { status: "success", summary: "Airline network fixture loaded.", crew: [] },
      },
    ],
  },
  "airline-scenarios": {
    id: "airline-scenarios",
    method: "GET",
    path: "/airline/scenarios",
    status: "pilot",
    title: "GET /airline/scenarios",
    summary: "List disruption scenarios for the OCC recovery demo.",
    auth: true,
    responseFields: [
      { name: "scenarios", type: "Scenario[]", required: true, description: "Scenario catalog." },
    ],
    examples: [{ label: "Scenarios", response: { status: "success", scenarios: [] } }],
  },
  "airline-disruption": {
    id: "airline-disruption",
    method: "GET",
    path: "/airline/disruption",
    status: "pilot",
    title: "GET /airline/disruption",
    summary: "Fetch disruption metadata for a scenario id.",
    auth: true,
    queryParams: [
      {
        name: "scenarioId",
        type: "string",
        required: false,
        default: "mx-hold-ord-0612",
        description: "Scenario identifier.",
      },
    ],
    examples: [
      {
        label: "MX hold",
        response: { status: "success", disruption: {}, scenario: {} },
      },
    ],
  },
  "airline-qpu-trace": {
    id: "airline-qpu-trace",
    method: "GET",
    path: "/airline/qpu-trace",
    status: "pilot",
    title: "GET /airline/qpu-trace",
    summary: "Cached QPU sampling trace for hybrid micro-window replay.",
    auth: true,
    examples: [{ label: "Trace", response: { status: "success", trace: {} } }],
  },
  "airline-upload-crew": {
    id: "airline-upload-crew",
    method: "POST",
    path: "/airline/upload-crew",
    status: "pilot",
    title: "POST /airline/upload-crew",
    summary: "Upload a CSV crew roster; returns a 24-hour session id.",
    auth: true,
    examples: [
      {
        label: "Upload",
        response: { status: "success", sessionId: "airline-...", summary: "Validated crew." },
      },
    ],
  },
  "airline-recover-solve": {
    id: "airline-recover-solve",
    method: "POST",
    path: "/airline/recover/solve",
    status: "pilot",
    title: "POST /airline/recover/solve",
    summary:
      "Run OCC recovery: tail routing, CP-SAT crew assignment, hybrid alternates, scoreboard, audit packs.",
    auth: true,
    requestFields: [
      {
        name: "scenarioId",
        type: "string",
        required: false,
        default: "mx-hold-ord-0612",
        description: "Disruption scenario.",
      },
      {
        name: "useFixture",
        type: "boolean",
        required: false,
        default: "true",
        description: "Replay cached QPU trace when true.",
      },
      {
        name: "crewSessionId",
        type: "string",
        required: false,
        description: "Uploaded crew session override.",
      },
      { name: "seed", type: "integer", required: false, default: "1234", description: "Seed." },
    ],
    responseFields: [
      { name: "routing", type: "RoutingResult", required: true, description: "Tail repair." },
      {
        name: "classicalPlan",
        type: "RecoveryPlan",
        required: true,
        description: "CP-SAT crew assignment.",
      },
      {
        name: "hybridPlans",
        type: "RecoveryPlan[]",
        required: true,
        description: "Hybrid alternates.",
      },
      { name: "scoreboard", type: "Scoreboard", required: true, description: "KPI comparison." },
      { name: "auditPacks", type: "AuditPack[]", required: true, description: "Audit artifacts." },
    ],
    examples: [
      {
        label: "Recover",
        request: { scenarioId: "mx-hold-ord-0612", useFixture: true, seed: 1234 },
        response: {
          status: "success",
          classicalPlan: {},
          hybridPlans: [],
          scoreboard: {},
        },
      },
    ],
  },
  "ev-fleet-depot": {
    id: "ev-fleet-depot",
    method: "GET",
    path: "/ev-fleet/depot",
    status: "pilot",
    title: "GET /ev-fleet/depot",
    summary: "Load fleet, stops, chargers, depot, and TOU tariff fixtures.",
    auth: true,
    examples: [{ label: "Depot", response: { status: "success", vehicles: [], stops: [] } }],
  },
  "ev-fleet-scenarios": {
    id: "ev-fleet-scenarios",
    method: "GET",
    path: "/ev-fleet/scenarios",
    status: "pilot",
    title: "GET /ev-fleet/scenarios",
    summary: "List EV fleet charging scenarios.",
    auth: true,
    examples: [{ label: "Scenarios", response: { status: "success", scenarios: [] } }],
  },
  "ev-fleet-window": {
    id: "ev-fleet-window",
    method: "GET",
    path: "/ev-fleet/window",
    status: "pilot",
    title: "GET /ev-fleet/window",
    summary: "Fetch charging window for a scenario id.",
    auth: true,
    queryParams: [
      {
        name: "scenarioId",
        type: "string",
        required: false,
        default: "tou-peak-ca",
        description: "Scenario identifier.",
      },
    ],
    examples: [{ label: "Window", response: { status: "success", window: {}, scenario: {} } }],
  },
  "ev-fleet-qpu-trace": {
    id: "ev-fleet-qpu-trace",
    method: "GET",
    path: "/ev-fleet/qpu-trace",
    status: "pilot",
    title: "GET /ev-fleet/qpu-trace",
    summary: "Cached QPU trace for charger-queue hybrid replay.",
    auth: true,
    examples: [{ label: "Trace", response: { status: "success", trace: {} } }],
  },
  "ev-fleet-upload-fleet": {
    id: "ev-fleet-upload-fleet",
    method: "POST",
    path: "/ev-fleet/upload-fleet",
    status: "pilot",
    title: "POST /ev-fleet/upload-fleet",
    summary: "Upload fleet.csv; returns a 24-hour session id.",
    auth: true,
    examples: [
      {
        label: "Upload",
        response: { status: "success", sessionId: "ev-fleet-...", summary: "Validated fleet." },
      },
    ],
  },
  "ev-fleet-upload-stops": {
    id: "ev-fleet-upload-stops",
    method: "POST",
    path: "/ev-fleet/upload-stops",
    status: "pilot",
    title: "POST /ev-fleet/upload-stops",
    summary: "Upload stops.csv; returns a 24-hour session id.",
    auth: true,
    examples: [
      {
        label: "Upload",
        response: { status: "success", sessionId: "ev-fleet-...", summary: "Validated stops." },
      },
    ],
  },
  "pqc-inventory": {
    id: "pqc-inventory",
    method: "GET",
    path: "/pqc/inventory",
    status: "pilot",
    title: "GET /pqc/inventory",
    summary: "Load bundled cryptographic asset inventory for the Q-Day scanner demo.",
    auth: true,
    examples: [{ label: "Inventory", response: { status: "success", inventory: [] } }],
  },
  "pqc-scenarios": {
    id: "pqc-scenarios",
    method: "GET",
    path: "/pqc/scenarios",
    status: "pilot",
    title: "GET /pqc/scenarios",
    summary: "List PQC scan scenarios (bank, gov contractor, healthcare).",
    auth: true,
    examples: [{ label: "Scenarios", response: { status: "success", scenarios: [] } }],
  },
  "pqc-target": {
    id: "pqc-target",
    method: "GET",
    path: "/pqc/target",
    status: "pilot",
    title: "GET /pqc/target",
    summary: "Fetch scan target and persona for a scenario id.",
    auth: true,
    queryParams: [
      { name: "scenarioId", type: "string", required: false, default: "bank-tls-inventory", description: "Scenario id" },
    ],
    examples: [{ label: "Target", response: { status: "success", target: {}, scenario: {} } }],
  },
  "pqc-handshake-trace": {
    id: "pqc-handshake-trace",
    method: "GET",
    path: "/pqc/handshake-trace",
    status: "pilot",
    title: "GET /pqc/handshake-trace",
    summary: "Cached ML-KEM hybrid handshake trace for demo replay.",
    auth: true,
    examples: [{ label: "Trace", response: { status: "success", trace: {} } }],
  },
  "pqc-standards": {
    id: "pqc-standards",
    method: "GET",
    path: "/pqc/standards",
    status: "pilot",
    title: "GET /pqc/standards",
    summary: "Compliance crosswalk (FIPS 203-205, CNSA 2.0, NSM-10, CMMC).",
    auth: true,
    examples: [{ label: "Standards", response: { status: "success", standards: {} } }],
  },
  "pqc-upload-bundle": {
    id: "pqc-upload-bundle",
    method: "POST",
    path: "/pqc/upload-bundle",
    status: "pilot",
    title: "POST /pqc/upload-bundle",
    summary: "Upload PEM cert bundle or CSV endpoint list; returns 24h session id.",
    auth: true,
    examples: [{ label: "Upload", response: { status: "success", sessionId: "pqc-...", summary: "Validated entries." } }],
  },
  "pqc-scan": {
    id: "pqc-scan",
    method: "POST",
    path: "/pqc/scan",
    status: "pilot",
    title: "POST /pqc/scan",
    summary: "Run Q-Day scan: inventory, Mosca risk, remediation backlog, handshake proof, report.",
    auth: true,
    requestFields: [
      { name: "scenarioId", type: "string", required: false, default: "bank-tls-inventory", description: "Scenario" },
      { name: "useFixture", type: "boolean", required: false, default: "true", description: "Fixture replay" },
      { name: "target", type: "string", required: false, description: "Override domain" },
      { name: "bundleSessionId", type: "string", required: false, description: "Upload session" },
    ],
    responseFields: [
      { name: "scoreboard", type: "RiskScoreboard", required: true, description: "Manual vs Qtangl" },
      { name: "assets", type: "CryptoAsset[]", required: true, description: "Discovered assets" },
      { name: "handshakeProof", type: "HandshakeProof", required: true, description: "PQ TLS proof" },
    ],
    examples: [
      {
        label: "Fixture scan",
        request: { scenarioId: "bank-tls-inventory", useFixture: true },
        response: { status: "success", scanId: "scan-...", scoreboard: {} },
      },
    ],
  },
  "pqc-scan-status": {
    id: "pqc-scan-status",
    method: "GET",
    path: "/pqc/scan/{scanId}",
    status: "pilot",
    title: "GET /pqc/scan/{scanId}",
    summary: "Poll live scan job status and timeline.",
    auth: true,
    examples: [{ label: "Running", response: { status: "running", scanId: "scan-...", timeline: [] } }],
  },
  "pqc-handshake-prove": {
    id: "pqc-handshake-prove",
    method: "POST",
    path: "/pqc/handshake/prove",
    status: "pilot",
    title: "POST /pqc/handshake/prove",
    summary: "Prove hybrid ML-KEM-768 TLS handshake (live or replayed).",
    auth: true,
    examples: [{ label: "Prove", request: { useFixture: true }, response: { status: "success", proof: {} } }],
  },
  "pqc-report": {
    id: "pqc-report",
    method: "GET",
    path: "/pqc/report/{scanId}",
    status: "pilot",
    title: "GET /pqc/report/{scanId}",
    summary: "Download migration report as json, csv, cbom, or pdf.",
    auth: true,
    queryParams: [
      { name: "format", type: "string", required: false, default: "json", description: "json|csv|cbom|pdf" },
    ],
    examples: [{ label: "JSON report", response: {} }],
  },
  "pqc-transparency": {
    id: "pqc-transparency",
    method: "GET",
    path: "/pqc/transparency/root",
    status: "pilot",
    title: "GET /pqc/transparency/*",
    summary:
      "Append-only transparency log: root hash, signing key history, and inclusion proofs for report content hashes.",
    auth: false,
    examples: [
      {
        label: "Log root",
        response: { status: "success", log: { seq: 42, rootHash: "abc…", entryCount: 42 } },
      },
      {
        label: "Inclusion proof",
        response: {
          status: "success",
          inclusion: { seq: 7, contentHash: "…", rootHash: "…", entryHash: "…" },
        },
      },
    ],
  },
  "pqc-cbom-ingest": {
    id: "pqc-cbom-ingest",
    method: "POST",
    path: "/pqc/cbom/ingest",
    status: "pilot",
    title: "POST /pqc/cbom/ingest",
    summary:
      "Ingest CycloneDX 1.6/1.7 CBOM from third-party tools; normalize, provenance-tag, and merge into tenant aggregate.",
    auth: true,
    examples: [
      {
        label: "Ingest JSON",
        request: { document: { bomFormat: "CycloneDX", specVersion: "1.6", version: 1, components: [] } },
        response: { status: "success", ok: true, componentCount: 12 },
      },
    ],
  },
  "ev-fleet-plan-solve": {
    id: "ev-fleet-plan-solve",
    method: "POST",
    path: "/ev-fleet/plan/solve",
    status: "pilot",
    title: "POST /ev-fleet/plan/solve",
    summary:
      "Run VRP routing, CP-SAT charger queue, hybrid stagger, scoreboard, and audit packs.",
    auth: true,
    requestFields: [
      {
        name: "scenarioId",
        type: "string",
        required: false,
        default: "tou-peak-ca",
        description: "Scenario identifier.",
      },
      {
        name: "useFixture",
        type: "boolean",
        required: false,
        default: "true",
        description: "Replay cached QPU trace when true.",
      },
      {
        name: "fleetSessionId",
        type: "string",
        required: false,
        description: "Uploaded fleet session override.",
      },
      {
        name: "stopsSessionId",
        type: "string",
        required: false,
        description: "Uploaded stops session override.",
      },
      {
        name: "seed",
        type: "integer",
        required: false,
        default: "1234",
        description: "Solver seed.",
      },
    ],
    responseFields: [
      { name: "routing", type: "RoutingResult", required: true, description: "VRP assignments." },
      {
        name: "classicalPlan",
        type: "ChargePlan",
        required: true,
        description: "CP-SAT charge plan.",
      },
      {
        name: "hybridPlans",
        type: "ChargePlan[]",
        required: true,
        description: "Hybrid staggered plans.",
      },
      { name: "scoreboard", type: "Scoreboard", required: true, description: "KPI comparison." },
      { name: "auditPacks", type: "AuditPack[]", required: true, description: "Audit artifacts." },
    ],
    examples: [
      {
        label: "Solve",
        request: { scenarioId: "tou-peak-ca", useFixture: true, seed: 1234 },
        response: { status: "success", classicalPlan: {}, hybridPlans: [], scoreboard: {} },
      },
    ],
  },
};

export function getEndpoint(id: string): DocsEndpoint | undefined {
  return docsEndpoints[id];
}
